Repository openkruise/kruise, pull requests merged in 2021-08, with the labels that each got.

#669 podunavailablebudget controller
  .github/workflows/ci.yaml
  pkg/control/pubcontrol/OWNERS
  pkg/control/pubcontrol/pub_control.go
  pkg/control/pubcontrol/util.go
  pkg/control/pubcontrol/utils.go
  pkg/control/sidecarcontrol/OWNERS
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/controller/controllers.go
  pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
  pkg/controller/podunavailablebudget/pub_controller_test.go
  pkg/controller/podunavailablebudget/pub_pod_event_handler.go
  pkg/controller/podunavailablebudget/pub_pod_event_handler_test.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/features/kruise_features.go
  pkg/util/controllerfinder/controller_finder.go
  pkg/util/controllerfinder/pods_finder.go
  pkg/webhook/pod/validating/pod_create_update_handler.go
  pkg/webhook/pod/validating/pod_unavailable_budget.go
  pkg/webhook/pod/validating/pod_unavailable_budget_test.go
  pkg/webhook/podunavailablebudget/validating/pub_create_update_handler.go
  test/e2e/apps/sidecarset.go
  test/e2e/framework/sidecarset_utils.go
Labels: approved, lgtm, size/XXL

#656 Add internal ContainerService and pod informer for kruise-daemon
  cmd/daemon/main.go
  config/rbac/daemon_role.yaml
  main.go
  pkg/daemon/containerrecreate/crr_daemon_controller.go
  pkg/daemon/criruntime/containerruntime/containerd.go
  pkg/daemon/criruntime/containerruntime/docker.go
  pkg/daemon/criruntime/containerruntime/interface.go
  pkg/daemon/criruntime/containerruntime/pouch.go
  pkg/daemon/criruntime/factory.go
  pkg/daemon/criruntime/imageruntime/containerd.go
  pkg/daemon/criruntime/imageruntime/docker.go
  pkg/daemon/criruntime/imageruntime/helpers.go
  pkg/daemon/criruntime/imageruntime/pouch.go
  pkg/daemon/criruntime/util.go
  pkg/daemon/daemon.go
  pkg/daemon/imagepuller/imagepuller_controller.go
  pkg/daemon/imagepuller/imagepuller_worker.go
  pkg/daemon/options/options.go
  pkg/daemon/util/error.go
  pkg/features/kruise_features.go
Labels: approved, size/XL

#691 add pub feature gates
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
  pkg/features/kruise_features.go
  pkg/webhook/pod/validating/pod_create_update_handler.go
  pkg/webhook/podunavailablebudget/validating/pub_create_update_handler.go
Labels: approved, lgtm, size/M

#693 fix e2e frequent failures of BroadcastJob
  test/e2e/apps/broadcastjob.go
Labels: approved, size/XS

#673 proposal: resource distribution
  docs/proposals/20210719-resourcedistribution.md
Labels: approved, size/L

#701 Make BroadcastJob e2e test more robust
  test/e2e/apps/broadcastjob.go
  test/e2e/framework/broadcastjob_util.go
  test/e2e/framework/node_util.go
Labels: lgtm, approved, size/M

#699 Fix the kruise exception caused by the change of container name in sidecarSet.
  pkg/control/sidecarcontrol/util.go
  pkg/controller/sidecarset/sidecarset_controller_test.go
  pkg/controller/sidecarset/sidecarset_hotupgrade_test.go
  pkg/controller/sidecarset/sidecarset_pod_event_handler.go
  pkg/controller/sidecarset/sidecarset_strategy_test.go
  pkg/webhook/pod/mutating/sidecarset.go
  pkg/webhook/sidecarset/validating/sidecarset_create_update_handler.go
  test/e2e/apps/sidecarset.go
Labels: lgtm, approved, size/L

#703 Add injection gate for SidecarSet
  apis/apps/v1alpha1/sidecarset_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_sidecarsets.yaml
  pkg/webhook/pod/mutating/sidecarset.go
  pkg/webhook/pod/mutating/sidecarset_test.go
Labels: lgtm, approved, size/M

#706 fix pod webhook pub evcition exception
  pkg/webhook/pod/validating/pod_unavailable_budget.go
Labels: lgtm, approved, size/XS

#712 fix: ds status is outdate, apiserver will refuse this request
  pkg/controller/daemonset/daemonset_util.go
Labels: lgtm, approved, size/M

#714 configure mutliple nodes in e2e kind cluster
  .github/workflows/ci.yaml
  Makefile
  scripts/uninstall.sh
  test/e2e/apps/broadcastjob.go
  test/e2e/apps/pullimages.go
  test/kind-conf.yaml
Labels: lgtm, approved, size/L

#720 Fix kubebuilder installation in workflow
  .github/workflows/ci.yaml
  test/e2e/apps/broadcastjob.go
  test/e2e/framework/node_util.go
Labels: approved, size/M

#721 Optimize broadcastjob e2e case, waiting fake node to be ready first
  .github/workflows/ci.yaml
  test/e2e/framework/node_util.go
Labels: approved, size/S

#725 support `-o wide` fields for kruise resources
  apis/apps/v1alpha1/cloneset_types.go
  apis/apps/v1alpha1/daemonset_types.go
  apis/apps/v1alpha1/statefulset_types.go
  apis/apps/v1beta1/statefulset_types.go
  config/crd/bases/apps.kruise.io_clonesets.yaml
  config/crd/bases/apps.kruise.io_daemonsets.yaml
  config/crd/bases/apps.kruise.io_statefulsets.yaml
Labels: lgtm, approved, size/M
