Repository openkruise/kruise, pull requests merged in 2021-07, with the labels that each got.

#655 adjust sidecarset control api interface UpdateSidecarContainerToLatest
  pkg/control/sidecarcontrol/api.go
  pkg/control/sidecarcontrol/sidecarset_control.go
  pkg/control/sidecarcontrol/util_hotupgrade.go
  pkg/controller/sidecarset/sidecarset_hotupgrade.go
  pkg/controller/sidecarset/sidecarset_pod_event_handler.go
  pkg/controller/sidecarset/sidecarset_processor.go
  pkg/controller/sidecarset/sidecarset_strategy.go
Labels: approved, lgtm, size/L

#657 fix rolling update stuck caused by deleting terminating pod
  pkg/controller/daemonset/update.go
Labels: approved, lgtm, size/XS

#650 podUnavailableBudget control
  pkg/control/pubcontrol/api.go
  pkg/control/pubcontrol/pub_control.go
  pkg/control/pubcontrol/util.go
  pkg/control/pubcontrol/validate_pub.go
  pkg/control/sidecarcontrol/sidecarset_control.go
  pkg/control/sidecarcontrol/util_test.go
  pkg/util/controllerfinder/controller_finder.go
  pkg/util/inplaceupdate/inplace_utils_test.go
  pkg/util/inplaceupdate/options.go
  test/e2e/apps/sidecarset.go
Labels: approved, lgtm, size/XXL

#668 Add stale config file
  .github/stale.yml
Labels: approved, lgtm, size/M

#664 ci: add golangci lint config
  .github/workflows/ci.yaml
  .golangci.yml
  pkg/features/kruise_features.go
  pkg/util/expectations/update_expectations.go
  pkg/webhook/util/crd/crd.go
Labels: approved, lgtm, size/M

#670 Update governance and link to the new community project
  ADOPTERS.md
  CODE_OF_CONDUCT.md
  FAQ.md
  GOVERNANCE.md
  MAINTAINERS.md
  OWNERS
  pkg/control/pubcontrol/OWNERS
  pkg/control/sidecarcontrol/OWNERS
  pkg/controller/cloneset/OWNERS
  pkg/controller/daemonset/OWNERS
  pkg/controller/sidecarset/OWNERS
Labels: approved, lgtm, size/L

#675 Add imagepullsecrets field for sidecarset
  apis/apps/v1alpha1/sidecarset_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_sidecarsets.yaml
  pkg/webhook/pod/mutating/sidecarset.go
  pkg/webhook/pod/mutating/sidecarset_test.go
Labels: approved, lgtm, size/L

#666 podUnavailableBudget for pod validate webhook
  PROJECT
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  config/webhook/patch_manifests.yaml
  main.go
  pkg/control/pubcontrol/validate_pub.go
  pkg/webhook/add_pod.go
  pkg/webhook/pod/validating/pod_create_update_handler.go
  pkg/webhook/pod/validating/pod_unavailable_budget.go
  pkg/webhook/pod/validating/pod_unavailable_budget_test.go
  pkg/webhook/pod/validating/webhooks.go
  vendor/k8s.io/apiserver/pkg/util/dryrun/dryrun.go
  vendor/k8s.io/kubernetes/pkg/apis/policy/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/policy/OWNERS
  vendor/k8s.io/kubernetes/pkg/apis/policy/doc.go
  vendor/k8s.io/kubernetes/pkg/apis/policy/register.go
  vendor/k8s.io/kubernetes/pkg/apis/policy/types.go
  vendor/k8s.io/kubernetes/pkg/apis/policy/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#654 Add proposal of WorkloadSpread, a bypass scheme for elasticity and multi-domain management
  docs/proposals/20210628-workloadspread.md
Labels: approved, lgtm, size/L

#672 proposal: sidecarset imagepullsecrets
  docs/proposals/20210713-sidecarsetimagepullsecrects.md
Labels: approved, lgtm, size/L

#682 update debug guide
  docs/debug/README.md
Labels: approved, lgtm, size/M

#679 fix updated pod cannot inplace update again
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/util/lifecycle/lifecycle_utils.go
Labels: approved, lgtm, size/M
