Repository openkruise/kruise, pull requests merged in 2021-12, with the labels that each got.

#830 break giant func down
  pkg/webhook/statefulset/validating/statefulset_validation.go
Labels: lgtm, approved, size/L

#829 Fix error adding pod Webhook module comment
  pkg/webhook/add_pod.go
Labels: lgtm, approved, size/XS

#831 fix pub e2e failed
  test/e2e/policy/podunavailablebudget.go
Labels: lgtm, approved, size/L

#819 Add SourceContainerNameFrom and EnvNames in sidecarset transferenv
  apis/apps/defaults/v1alpha1.go
  apis/apps/v1alpha1/sidecarset_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_sidecarsets.yaml
  pkg/control/sidecarcontrol/util.go
  pkg/control/sidecarcontrol/util_test.go
  pkg/webhook/sidecarset/validating/sidecarset_create_update_handler.go
  test/e2e/apps/sidecarset.go
Labels: lgtm, approved, size/XL

#823 Make workloadSpread more robust and easily-used.
  config/webhook/manifests.yaml
  pkg/controller/workloadspread/reschedule.go
  pkg/controller/workloadspread/update_pod_deletion_cost.go
  pkg/controller/workloadspread/workloadspread_controller.go
  pkg/controller/workloadspread/workloadspread_controller_test.go
  pkg/controller/workloadspread/workloadspread_controller_utils.go
  pkg/webhook/workloadspread/validating/workloadspread_validation.go
  pkg/webhook/workloadspread/validating/workloadspread_validation_test.go
  test/e2e/apps/workloadspread.go
Labels: lgtm, approved, size/XL

#821 add ephemeral job finalizer
  pkg/controller/ephemeraljob/econtainer/econtainer_k8s.go
  pkg/controller/ephemeraljob/ephemeraljob_controller.go
  pkg/controller/ephemeraljob/ephemeraljob_utils.go
Labels: lgtm, approved, size/M

#837 performance enhance
  pkg/util/imagejob/imagejob_reader.go
Labels: lgtm, approved, size/XS

#833 add ephemeral container inplace update e2e test
  test/e2e/apps/ephemeraljob.go
Labels: lgtm, approved, size/L

#843 do not exit when webhook ready timeout
  pkg/webhook/server.go
Labels: lgtm, approved, size/XS

#845 fix #844 When updating statefullset, the total number of pods being u…
  pkg/controller/statefulset/stateful_set_control.go
Labels: lgtm, approved, size/XS

#841 open daemon pprof
  cmd/daemon/main.go
  main.go
Labels: lgtm, approved, size/S

#846 Add changelog for v1.0.0
  CHANGELOG.md
  README-zh_CN.md
  README.md
Labels: lgtm, approved, size/M

#848 Update README for community
  README-zh_CN.md
  README.md
Labels: lgtm, approved, size/XS

#852 Add changelog for v0.10.2
  CHANGELOG.md
Labels: lgtm, approved, size/S

#850 SidecarSet hot upgrade containers should be consistent with pod's
  apis/apps/v1alpha1/sidecarset_types.go
  config/crd/bases/apps.kruise.io_sidecarsets.yaml
  pkg/control/sidecarcontrol/util.go
  pkg/controller/sidecarset/sidecarset_hotupgrade_test.go
  pkg/controller/sidecarset/sidecarset_pod_event_handler.go
  pkg/controller/sidecarset/sidecarset_processor.go
  pkg/controller/sidecarset/sidecarset_processor_test.go
  pkg/webhook/pod/mutating/sidecarset.go
  test/e2e/framework/sidecarset_utils.go
Labels: lgtm, approved, size/M

#860 Fix log error when extract container from fieldpath failed
  pkg/control/sidecarcontrol/util.go
Labels: lgtm, approved, size/XS

#854 optimization to determine whether the pod state is consistent logic
  pkg/control/sidecarcontrol/sidecarset_control.go
  pkg/util/pods.go
Labels: lgtm, approved, size/S

#864 allow to update asts RevisionHistoryLimit
  pkg/webhook/statefulset/validating/statefulset_validation.go
Labels: lgtm, approved, size/XS

#861 Fix bugs for ResourceDistribution
  Makefile
  apis/apps/v1alpha1/resourcedistribution_types.go
  config/crd/bases/apps.kruise.io_resourcedistributions.yaml
  pkg/controller/resourcedistribution/resourcedistribution_controller.go
  pkg/controller/resourcedistribution/resourcedistribution_controller_test.go
  pkg/controller/resourcedistribution/utils.go
  pkg/webhook/resourcedistribution/validating/resourcedistribution_create_update_handler.go
  pkg/webhook/resourcedistribution/validating/resourcedistribution_validating_test.go
  pkg/webhook/resourcedistribution/validating/utils.go
  test/e2e/apps/resourcedistribution.go
  test/e2e/framework/resourcedistribution_utils.go
Labels: lgtm, approved, size/L

#868 simplify syncNodeImages func
  pkg/controller/imagepulljob/imagepulljob_controller.go
  pkg/controller/imagepulljob/imagepulljob_utils.go
  pkg/util/pods.go
Labels: lgtm, approved, size/M

#715 store history revisions for sidecarset
  apis/apps/defaults/v1alpha1.go
  apis/apps/v1alpha1/sidecarset_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_sidecarsets.yaml
  pkg/control/sidecarcontrol/history_control.go
  pkg/control/sidecarcontrol/util.go
  pkg/controller/sidecarset/sidecarset_controller.go
  pkg/controller/sidecarset/sidecarset_controller_test.go
  pkg/controller/sidecarset/sidecarset_hotupgrade_test.go
  pkg/controller/sidecarset/sidecarset_processor.go
  pkg/controller/sidecarset/sidecarset_processor_test.go
  pkg/controller/sidecarset/sidecarset_strategy_test.go
  test/e2e/apps/sidecarset.go
  test/e2e/framework/sidecarset_utils.go
Labels: lgtm, approved, size/XL

#870 Update contributing docs
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yaml
  CONTRIBUTING.md
  Dockerfile
  Makefile
  docs/contributing/BUMP_KUBERNETS_VERSION.md
  docs/contributing/DEBUG.md
  hack/tools.go
  pkg/util/inplaceupdate/inplace_update_defaults.go
  scripts/generate_bindata.sh
  vendor/github.com/go-bindata/go-bindata/go-bindata/.gitignore
  vendor/github.com/go-bindata/go-bindata/go-bindata/AppendSliceValue.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/main.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/version.go
  vendor/modules.txt
Labels: lgtm, approved, size/L
