Repository openkruise/kruise, pull requests merged in 2021-11, with the labels that each got.

#795 Add DiscoverGVK for WorkloadSpread
  pkg/controller/workloadspread/workloadspread_controller.go
Labels: lgtm, approved, size/XS

#729 add feature ephemeral job controller
  .github/workflows/e2e-1.16.yaml
  .github/workflows/e2e-1.18.yaml
  .github/workflows/e2e-1.22.yaml
  apis/apps/v1alpha1/ephemeraljob_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_ephemeraljobs.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_ephemeraljobs.yaml
  config/rbac/ephemeraljob_editor_role.yaml
  config/rbac/ephemeraljob_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/apps_v1alpha1_ephemeraljob.yaml
  pkg/controller/controllers.go
  pkg/controller/ephemeraljob/econtainer/api.go
  pkg/controller/ephemeraljob/econtainer/econtainer_k8s.go
  pkg/controller/ephemeraljob/ephemeraljob_controller.go
  pkg/controller/ephemeraljob/ephemeraljob_event_handler.go
  pkg/controller/ephemeraljob/ephemeraljob_utils.go
  test/e2e/apps/ephemeraljob.go
  test/e2e/framework/ephemeraljob_utils.go
  test/kind-conf.yaml
Labels: lgtm, approved, size/XXL

#800 Fix e2e failure for containerlaunchpriority
  test/e2e/apps/containerlaunchpriority.go
Labels: lgtm, approved, size/M

#802 Fix e2e failure for pulling image
  test/e2e/apps/pullimages.go
Labels: lgtm, approved, size/XS

#798 Generate CRDs with original controller-tools and markers
  Makefile
  apis/apps/v1alpha1/advancedcronjob_types.go
  apis/apps/v1alpha1/broadcastjob_types.go
  apis/apps/v1alpha1/cloneset_types.go
  apis/apps/v1alpha1/daemonset_types.go
  apis/apps/v1alpha1/ephemeraljob_types.go
  apis/apps/v1alpha1/resourcedistribution_types.go
  apis/apps/v1alpha1/sidecarset_types.go
  apis/apps/v1alpha1/statefulset_types.go
  apis/apps/v1alpha1/uniteddeployment_types.go
  apis/apps/v1alpha1/workloadspread_types.go
  apis/apps/v1beta1/statefulset_types.go
  config/crd/bases/apps.kruise.io_advancedcronjobs.yaml
  config/crd/bases/apps.kruise.io_broadcastjobs.yaml
  config/crd/bases/apps.kruise.io_clonesets.yaml
  config/crd/bases/apps.kruise.io_containerrecreaterequests.yaml
  config/crd/bases/apps.kruise.io_daemonsets.yaml
  config/crd/bases/apps.kruise.io_ephemeraljobs.yaml
  config/crd/bases/apps.kruise.io_imagepulljobs.yaml
  config/crd/bases/apps.kruise.io_nodeimages.yaml
  config/crd/bases/apps.kruise.io_resourcedistributions.yaml
  config/crd/bases/apps.kruise.io_sidecarsets.yaml
  config/crd/bases/apps.kruise.io_statefulsets.yaml
  config/crd/bases/apps.kruise.io_uniteddeployments.yaml
  config/crd/bases/apps.kruise.io_workloadspreads.yaml
  config/crd/bases/policy.kruise.io_podunavailablebudgets.yaml
Labels: lgtm, approved, size/XXL

#806 Add change log for v0.10.1 and v1.0.0-alpha.2
  CHANGELOG.md
Labels: lgtm, approved, size/M

#808 Fix pod NodeSelectorTerms length 0 when UnitedDeployment NodeSelector…
  pkg/controller/uniteddeployment/adapter/adapter_util.go
Labels: lgtm, approved, size/XS

#763 Add scaleStrategy.maxUnavailable for CloneSet
  apis/apps/v1alpha1/cloneset_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_clonesets.yaml
  config/crd/bases/apps.kruise.io_uniteddeployments.yaml
  pkg/controller/cloneset/sync/cloneset_scale.go
  pkg/controller/cloneset/sync/cloneset_sync_utils.go
  pkg/controller/cloneset/sync/cloneset_sync_utils_test.go
  test/e2e/apps/cloneset.go
Labels: lgtm, approved, size/L

#815 feat: create daemon pod according to progressive flag in manage phase…
  pkg/controller/daemonset/daemonset_controller.go
  pkg/controller/daemonset/daemonset_util.go
  pkg/controller/daemonset/daemonset_util_test.go
Labels: lgtm, approved, size/L

#820 Mark revision stable when all pods updated to it
  pkg/controller/cloneset/cloneset_status.go
  pkg/util/imagejob/utilfunction/imagejob_util.go
  test/e2e/apps/cloneset.go
Labels: lgtm, approved, size/S

#822 Add changelog for v1.0.0-beta.0
  CHANGELOG.md
Labels: lgtm, approved, size/S

#824 Fix `api path` in PROJECT file
  PROJECT
Labels: lgtm, approved, size/S
