Repository openkruise/kruise, pull requests merged in 2021-09, with the labels that each got.

#698 Add controller for ResourceDistribution
  apis/apps/v1alpha1/resourcedistribution_types.go
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  go.sum
  pkg/controller/controllers.go
  pkg/controller/resourcedistribution/resourcedistribution_controller.go
  pkg/controller/resourcedistribution/resourcedistribution_namespace_event_handler.go
  pkg/controller/resourcedistribution/utils.go
  pkg/webhook/resourcedistribution/validating/resourcedistribution_create_update_handler.go
  pkg/webhook/resourcedistribution/validating/utils.go
Labels: lgtm, approved, size/XL

#735 using TemplateNoDefaults to control pod and pvc template defaults
  apis/apps/defaults/v1alpha1.go
  apis/apps/defaults/v1beta1.go
  pkg/features/kruise_features.go
  pkg/webhook/advancedcronjob/mutating/advancedcronjob_create_update_handler.go
  pkg/webhook/broadcastjob/mutating/broadcastjob_create_update_handler.go
  pkg/webhook/cloneset/mutating/cloneset_create_update_handler.go
  pkg/webhook/statefulset/mutating/statefulset_create_update_handler.go
  pkg/webhook/uniteddeployment/mutating/uniteddeployment_create_update_handler.go
Labels: lgtm, approved, size/L

#734 Optimize workloadspread feature-gate and object decode for pod deletion
  pkg/features/kruise_features.go
  pkg/util/workloadspread/workloadspread.go
  pkg/webhook/pod/mutating/pod_create_update_handler.go
  pkg/webhook/pod/validating/pod_create_update_handler.go
  test/e2e/apps/containerrecreate.go
Labels: lgtm, approved, size/M

#736 Preparing for v0.10.0 release
  CHANGELOG.md
  README-zh_CN.md
  README.md
  charts/kruise/v0.10.0/.helmignore
  charts/kruise/v0.10.0/Chart.yaml
  charts/kruise/v0.10.0/README.md
  charts/kruise/v0.10.0/templates/_helpers.tpl
  charts/kruise/v0.10.0/templates/apps.kruise.io_advancedcronjobs.yaml
  charts/kruise/v0.10.0/templates/apps.kruise.io_broadcastjobs.yaml
  charts/kruise/v0.10.0/templates/apps.kruise.io_clonesets.yaml
  charts/kruise/v0.10.0/templates/apps.kruise.io_containerrecreaterequests.yaml
  charts/kruise/v0.10.0/templates/apps.kruise.io_daemonsets.yaml
  charts/kruise/v0.10.0/templates/apps.kruise.io_imagepulljobs.yaml
  charts/kruise/v0.10.0/templates/apps.kruise.io_nodeimages.yaml
  charts/kruise/v0.10.0/templates/apps.kruise.io_sidecarsets.yaml
  charts/kruise/v0.10.0/templates/apps.kruise.io_statefulsets.yaml
  charts/kruise/v0.10.0/templates/apps.kruise.io_uniteddeployments.yaml
  charts/kruise/v0.10.0/templates/apps.kruise.io_workloadspreads.yaml
  charts/kruise/v0.10.0/templates/manager.yaml
  charts/kruise/v0.10.0/templates/policy.kruise.io_podunavailablebudgets.yaml
  charts/kruise/v0.10.0/templates/rbac_role.yaml
  charts/kruise/v0.10.0/templates/webhookconfiguration.yaml
  charts/kruise/v0.10.0/values.yaml
  pkg/features/kruise_features.go
Labels: approved, size/XXL

#738 Update description for PUB/WorkloadSpread in README-cn
  README-zh_CN.md
Labels: size/XS

#713 fix inplace_update for daemonset and support inplace
  pkg/controller/daemonset/daemonset_util.go
  pkg/controller/daemonset/inplace_update.go
  pkg/controller/daemonset/update.go
  pkg/util/inplaceupdate/inplace_utils.go
  test/e2e/apps/daemonset.go
  test/e2e/framework/daemonset_util.go
Labels: lgtm, approved, size/L

#742 fix(sidecarset): filter active pods with kubecontroller.IsPodActive
  pkg/control/sidecarcontrol/util.go
Labels: lgtm, approved, size/XS

#740 Add E2E test for WorkloadSpread
  apis/apps/v1alpha1/workloadspread_types.go
  config/crd/bases/apps.kruise.io_workloadspreads.yaml
  pkg/controller/workloadspread/workloadspread_controller.go
  pkg/controller/workloadspread/workloadspread_controller_test.go
  pkg/controller/workloadspread/workloadspread_event_handler.go
  test/e2e/apps/workloadspread.go
  test/e2e/framework/workloadspread_util.go
Labels: lgtm, approved, size/XXL

#726 Add security doc and actions
  SECURITY.md
  test/e2e/apps/broadcastjob.go
Labels: lgtm, approved, size/M

#707 daemon reports runtime-container-meta to support in-place update with same imageID
  apis/apps/pub/inplace_update.go
  apis/apps/pub/zz_generated.deepcopy.go
  pkg/daemon/containermeta/container_meta_controller.go
  pkg/daemon/criruntime/containerruntime/containerd.go
  pkg/daemon/criruntime/containerruntime/docker.go
  pkg/daemon/criruntime/containerruntime/interface.go
  pkg/daemon/criruntime/containerruntime/pouch.go
  pkg/daemon/criruntime/factory.go
  pkg/daemon/daemon.go
  pkg/util/inplaceupdate/inplace_update.go
  pkg/util/inplaceupdate/inplace_update_defaults.go
  pkg/util/inplaceupdate/inplace_update_test.go
  test/e2e/apps/cloneset.go
  test/e2e/framework/cloneset_util.go
Labels: lgtm, approved, size/XL

#750 Add a new linter and address related issues
  .golangci.yml
  pkg/controller/uniteddeployment/allocator_test.go
Labels: lgtm, approved, size/M

#751 Fix e2e bug for workloadspread
  test/e2e/apps/workloadspread.go
  test/e2e/framework/workloadspread_util.go
Labels: lgtm, approved, size/M

#757 make command generate all resouce
  Makefile
Labels: lgtm, approved, size/XS

#749 Optimize WorkloadSpread via reducing update conflicts
  pkg/controller/workloadspread/workloadspread_controller.go
  pkg/util/cache.go
  pkg/util/cache_test.go
  pkg/util/lock.go
  pkg/util/lock_test.go
  pkg/util/workloadspread/workloadspread.go
  pkg/util/workloadspread/workloadspread_test.go
Labels: lgtm, approved, size/L

#760 Update debug guide document
  CONTRIBUTING.md
  docs/debug/README.md
Labels: lgtm, approved, size/L

#716 Add unit test and e2e test for ResourceDistribution controller
  pkg/controller/resourcedistribution/resourcedistribution_controller_test.go
  pkg/controller/resourcedistribution/resourcedistribution_namespace_event_handler_test.go
  pkg/controller/resourcedistribution/utils_test.go
  test/e2e/apps/resourcedistribution.go
  test/e2e/framework/resourcedistribution_utils.go
Labels: lgtm, approved, size/XXL

#700 Add proposal for ContainerPriority
  docs/proposals/20210809-containerlaunchpriority.md
Labels: lgtm, approved, size/L

#756 add ephemeral job api
  apis/apps/v1alpha1/ephemeraljob_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_ephemeraljobs.yaml
  pkg/client/clientset/versioned/typed/apps/v1alpha1/apps_client.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/ephemeraljob.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/fake/fake_apps_client.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/fake/fake_ephemeraljob.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/apps/v1alpha1/ephemeraljob.go
  pkg/client/informers/externalversions/apps/v1alpha1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/apps/v1alpha1/ephemeraljob.go
  pkg/client/listers/apps/v1alpha1/expansion_generated.go
Labels: approved, size/XXL

#758 add pub interface GetPodsForPub
  apis/policy/v1alpha1/podunavailablebudget_types.go
  config/crd/bases/policy.kruise.io_podunavailablebudgets.yaml
  pkg/control/pubcontrol/api.go
  pkg/control/pubcontrol/pub_control.go
  pkg/control/pubcontrol/utils_test.go
  pkg/controller/cloneset/sync/api.go
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/controller/cloneset/sync/cloneset_update_test.go
  pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
  pkg/controller/podunavailablebudget/pub_controller_test.go
  pkg/controller/podunavailablebudget/pub_pod_event_handler.go
  pkg/util/controllerfinder/controller_finder.go
  pkg/webhook/pod/validating/pod_unavailable_budget.go
  test/e2e/apps/sidecarset.go
  test/e2e/apps/sidecarset_hotupgrade.go
  test/e2e/framework/podunavailablebudget_util.go
  test/e2e/framework/sidecarset_utils.go
  test/e2e/policy/podunavailablebudget.go
Labels: lgtm, approved, size/XXL

#762 export sync-seconds to control resource resync frequency
  main.go
Labels: lgtm, approved, size/S

#767 Update docs with new official website
  .github/workflows/ci.yaml
  CHANGELOG.md
  README-zh_CN.md
  README.md
  docs/README.md
Labels: lgtm, approved, size/L
