Repository openkruise/kruise, pull requests merged in 2022-11, with the labels that each got.

#1071 Add PreNormal Lifecycle Hook for CloneSet
  apis/apps/pub/lifecycle.go
  apis/apps/pub/zz_generated.deepcopy.go
  apis/apps/v1alpha1/cloneset_types.go
  config/crd/bases/apps.kruise.io_clonesets.yaml
  config/crd/bases/apps.kruise.io_daemonsets.yaml
  config/crd/bases/apps.kruise.io_statefulsets.yaml
  config/crd/bases/apps.kruise.io_uniteddeployments.yaml
  pkg/controller/cloneset/sync/cloneset_scale.go
  pkg/controller/cloneset/sync/cloneset_scale_test.go
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/controller/cloneset/sync/cloneset_update_test.go
  pkg/util/podreadiness/pod_readiness_utils.go
Labels: lgtm, approved, size/XL

#1124 cloneset partition support float percent
  pkg/util/tools.go
  pkg/util/tools_test.go
  pkg/webhook/cloneset/validating/validation.go
Labels: lgtm, approved, size/L

#1125 improve error hanlding of inplace update env from metadata
  pkg/controller/containerrecreaterequest/crr_controller.go
  pkg/util/inplaceupdate/inplace_update_defaults.go
  pkg/util/lifecycle/lifecycle_utils.go
  pkg/util/podreadiness/pod_readiness.go
  pkg/util/podreadiness/pod_readiness_utils_test.go
Labels: lgtm, approved, size/M

#1126 pub support to configure Evict,Delete,Update Operation
  apis/policy/v1alpha1/podunavailablebudget_types.go
  pkg/control/pubcontrol/pub_control_utils.go
  pkg/webhook/pod/validating/pod_unavailable_budget.go
  test/e2e/policy/podunavailablebudget.go
Labels: lgtm, approved, size/M

#1127 Make ephemeralJob compatible with k8s version 1.20 & 1.21
  .github/workflows/e2e-1.20.yaml
  pkg/controller/ephemeraljob/econtainer/econtainer_k8s.go
  test/e2e/apps/ephemeraljob.go
Labels: lgtm, approved, size/L
