Repository openkruise/kruise, pull requests merged in 2022-01, with the labels that each got.

#880 fix #879 Statefulset should consider non-available pods when deleting…
  pkg/controller/statefulset/stateful_set_control.go
Labels: lgtm, approved, size/XS

#886 feat: bump build tag
  .github/workflows/ci.yaml
  apis/apps/pub/zz_generated.deepcopy.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  apis/apps/v1beta1/zz_generated.deepcopy.go
  apis/policy/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved, size/XS

#887 break the loop when we find the current revision
  pkg/controller/cloneset/cloneset_controller.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/controller/uniteddeployment/revision.go
Labels: lgtm, approved, size/XS

#888 remove duplicate register fieldindexes in cloneset controller
  pkg/controller/cloneset/cloneset_controller.go
Labels: lgtm, approved, size/XS

#889 fix cloneset controller ut
  pkg/controller/cloneset/cloneset_controller_test.go
Labels: lgtm, approved, size/XS

#893 CloneSet refresh pod states before skipping update when paused
  pkg/controller/cloneset/sync/cloneset_update.go
  test/e2e/apps/cloneset.go
Labels: lgtm, approved, size/M

#885 replace reflect with generation
  pkg/controller/sidecarset/sidecarset_controller.go
Labels: lgtm, approved, size/XS

#896 Add changelog for v1.0.1
  CHANGELOG.md
Labels: lgtm, approved, size/M

#899 Make maxUnavailable also limited to pods in new revision
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/controller/cloneset/sync/cloneset_update_test.go
Labels: lgtm, approved, size/L

#897 Fix transferEnv in initContainer
  pkg/webhook/pod/mutating/sidecarset.go
  pkg/webhook/pod/mutating/sidecarset_test.go
Labels: lgtm, approved, size/S
