Repository openkruise/kruise, pull requests merged in 2022-03, with the labels that each got.

#917 add kruise_manager_is_leader metric
  main.go
  pkg/util/metrics/leadership/leader.go
  vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#920 nodes updated with labels matching update selector should be added to the queue in daemonset controller
  pkg/controller/daemonset/daemonset_event_handler.go
  pkg/controller/daemonset/daemonset_util.go
  pkg/controller/daemonset/daemonset_util_test.go
Labels: lgtm, approved, size/M

#916 Disable DeepCopy for some specific cache list
  .github/workflows/e2e-1.16.yaml
  .github/workflows/e2e-1.23.yaml
  config/manager/manager.yaml
  main.go
  pkg/controller/cloneset/cloneset_controller.go
  pkg/controller/cloneset/sync/cloneset_scale.go
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/controller/cloneset/sync/cloneset_update_test.go
  pkg/controller/cloneset/utils/cloneset_utils.go
  pkg/controller/sidecarset/sidecarset_processor.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/controller/statefulset/stateful_set_control_test.go
  pkg/util/client/delegating_client.go
  pkg/util/client/no_deepcopy_lister.go
  pkg/util/controllerfinder/pods_finder.go
  pkg/util/imagejob/imagejob_reader.go
  pkg/util/inplaceupdate/inplace_update.go
  pkg/util/lifecycle/lifecycle_utils.go
  pkg/util/podadapter/adapter.go
  pkg/util/refmanager/ref_manager.go
  pkg/webhook/pod/mutating/sidecarset.go
  test/e2e/apps/sidecarset.go
  test/e2e/apps/sidecarset_hotupgrade.go
  test/e2e/framework/statefulset_utils.go
  test/e2e/policy/podunavailablebudget.go
Labels: lgtm, approved, size/XL

#923 Support preDelete lifecycle for Advanced DaemonSet
  CONTRIBUTING.md
  Makefile
  apis/apps/v1alpha1/daemonset_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_daemonsets.yaml
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/controller/daemonset/daemonset_controller.go
  pkg/controller/daemonset/daemonset_controller_test.go
  pkg/controller/daemonset/daemonset_update.go
  pkg/controller/daemonset/daemonset_update_test.go
  pkg/controller/daemonset/daemonset_util.go
  pkg/util/inplaceupdate/inplace_update.go
  pkg/webhook/daemonset/validating/daemonset_validating_handler.go
  test/e2e/apps/daemonset.go
  test/e2e/framework/daemonset_util.go
Labels: lgtm, approved, size/L

#909 Support in-place update containers with launch priority
  Makefile
  apis/apps/pub/inplace_update.go
  apis/apps/pub/zz_generated.deepcopy.go
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/controller/cloneset/sync/cloneset_update_test.go
  pkg/controller/containerlaunchpriority/container_launch_priority_controller.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/util/containerlaunchpriority/container_launch_prirotiy.go
  pkg/util/containermeta/env_hash.go
  pkg/util/inplaceupdate/inplace_update.go
  pkg/util/inplaceupdate/inplace_update_defaults.go
  pkg/util/inplaceupdate/inplace_update_defaults_test.go
  pkg/util/inplaceupdate/inplace_update_test.go
  test/e2e/apps/cloneset.go
  test/e2e/apps/types.go
Labels: lgtm, approved, size/XXL

#930 Support cri-o imageruntime
  pkg/daemon/criruntime/factory.go
  pkg/daemon/criruntime/imageruntime/crio.go
Labels: lgtm, approved, size/L

#931 Optimize inplace update and support pod-template-hash label for cloneset
  pkg/controller/cloneset/cloneset_controller.go
  pkg/controller/cloneset/cloneset_event_handler.go
  pkg/controller/cloneset/sync/api.go
  pkg/controller/cloneset/sync/cloneset_scale_test.go
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/controller/cloneset/sync/cloneset_update_test.go
  pkg/controller/cloneset/utils/cloneset_utils.go
  test/e2e/framework/podunavailablebudget_util.go
  test/e2e/framework/workloadspread_util.go
  test/e2e/policy/podunavailablebudget.go
Labels: lgtm, approved, size/L

#929 fix:add volumes that initcontainers used in sidecarset
  pkg/webhook/pod/mutating/sidecarset.go
Labels: lgtm, approved, size/XS

#936 Support common CRI runtime based on cri-o impl
  pkg/daemon/criruntime/factory.go
  pkg/daemon/criruntime/imageruntime/cri.go
  pkg/daemon/imagepuller/imagepuller_worker.go
Labels: lgtm, approved, size/M

#882 Support StatefulSetAutoDeletePVC feature
  apis/apps/defaults/v1beta1.go
  apis/apps/v1beta1/statefulset_types.go
  apis/apps/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_statefulsets.yaml
  config/crd/bases/apps.kruise.io_uniteddeployments.yaml
  go.sum
  pkg/controller/statefulset/stateful_pod_control.go
  pkg/controller/statefulset/stateful_pod_control_test.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/controller/statefulset/stateful_set_control_test.go
  pkg/controller/statefulset/stateful_set_status_updater.go
  pkg/controller/statefulset/stateful_set_status_updater_test.go
  pkg/controller/statefulset/stateful_set_utils.go
  pkg/controller/statefulset/stateful_set_utils_test.go
  pkg/controller/statefulset/stateful_update_utils.go
  pkg/controller/statefulset/stateful_update_utils_test.go
  pkg/controller/statefulset/statefulset_controller.go
  pkg/controller/statefulset/statefulset_controller_suite_test.go
  pkg/controller/statefulset/statefulset_controller_test.go
  pkg/controller/statefulset/statefulset_predownload_image.go
  pkg/features/kruise_features.go
  pkg/util/feature/testing.go
  pkg/webhook/statefulset/validating/statefulset_validation.go
  test/e2e/apps/statefulset.go
  test/e2e/framework/pv_util.go
  test/e2e/framework/statefulset_utils.go
  test/e2e/manifest/manifest.go
Labels: lgtm, approved, size/XXL

#938 Add changelog for v1.1.0
  CHANGELOG.md
  README-zh_CN.md
  README.md
Labels: lgtm, size/M

#940 Optimize expectations for Advanced DaemonSet
  pkg/controller/daemonset/daemonset_controller.go
  pkg/controller/daemonset/daemonset_event_handler.go
Labels: lgtm, approved, size/M
