Repository openkruise/kruise, pull requests merged in 2022-05, with the labels that each got.

#955 performance optimization pub
  pkg/control/pubcontrol/api.go
  pkg/control/pubcontrol/pub_control.go
  pkg/control/pubcontrol/utils.go
  pkg/control/pubcontrol/utils_test.go
  pkg/control/sidecarcontrol/sidecarset_control.go
  pkg/control/sidecarcontrol/util.go
  pkg/control/sidecarcontrol/util_hotupgrade.go
  pkg/controller/cloneset/sync/api.go
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/controller/cloneset/sync/cloneset_update_test.go
  pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
  pkg/controller/podunavailablebudget/pub_controller_test.go
  pkg/controller/podunavailablebudget/pub_pod_event_handler.go
  pkg/controller/podunavailablebudget/pub_pod_event_handler_test.go
  pkg/controller/resourcedistribution/resourcedistribution_controller_test.go
  pkg/controller/sidecarset/sidecarset_hotupgrade.go
  pkg/controller/sidecarset/sidecarset_pod_event_handler.go
  pkg/util/controllerfinder/controller_finder.go
  pkg/webhook/pod/mutating/pod_create_update_handler.go
  pkg/webhook/pod/mutating/sidecarset.go
  pkg/webhook/pod/validating/pod_create_update_handler.go
  pkg/webhook/pod/validating/pod_unavailable_budget.go
  pkg/webhook/pod/validating/pod_unavailable_budget_test.go
  test/e2e/apps/daemonset.go
  test/e2e/apps/resourcedistribution.go
  test/e2e/apps/sidecarset.go
  test/e2e/apps/sidecarset_hotupgrade.go
  test/e2e/framework/daemonset_util.go
  test/e2e/framework/ephemeraljob_utils.go
  test/e2e/framework/podunavailablebudget_util.go
  test/e2e/framework/resourcedistribution_utils.go
  test/e2e/framework/sidecarset_utils.go
  test/e2e/policy/podunavailablebudget.go
Labels: lgtm, approved, size/XL

#971 fix pub patch pod annotation fail
  pkg/control/pubcontrol/pub_control.go
  pkg/control/pubcontrol/utils.go
  pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
  pkg/controller/podunavailablebudget/pub_pod_event_handler.go
  pkg/controller/workloadspread/workloadspread_controller.go
  pkg/util/controllerfinder/pods_finder.go
  pkg/webhook/pod/mutating/pod_create_update_handler.go
  pkg/webhook/pod/mutating/pod_unavailable_budget.go
  test/e2e/policy/podunavailablebudget.go
Labels: lgtm, approved, size/L

#978 clean up diff subsets
  pkg/controller/uniteddeployment/uniteddeployment_update.go
Labels: lgtm, approved, size/S

#979 Add mark pod not ready feature to Lifecycle hooks
  apis/apps/pub/lifecycle.go
  apis/apps/pub/pod_readiness_gate.go
  config/crd/bases/apps.kruise.io_clonesets.yaml
  config/crd/bases/apps.kruise.io_daemonsets.yaml
  config/crd/bases/apps.kruise.io_statefulsets.yaml
  config/crd/bases/apps.kruise.io_uniteddeployments.yaml
  pkg/controller/cloneset/cloneset_status.go
  pkg/controller/cloneset/sync/cloneset_scale.go
  pkg/controller/cloneset/sync/cloneset_sync_utils.go
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/controller/containerrecreaterequest/crr_controller.go
  pkg/controller/daemonset/daemonset_controller.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/util/lifecycle/lifecycle_utils.go
  pkg/util/podreadiness/pod_readiness.go
  pkg/util/podreadiness/pod_readiness_utils.go
  pkg/util/podreadiness/pod_readiness_utils_test.go
Labels: lgtm, approved, size/L

#968 persistent pod state controller
  Makefile
  apis/apps/v1alpha1/persistent_pod_state_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_persistentpodstates.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  pkg/client/clientset/versioned/typed/apps/v1alpha1/apps_client.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/fake/fake_apps_client.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/fake/fake_persistentpodstate.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/persistentpodstate.go
  pkg/client/informers/externalversions/apps/v1alpha1/interface.go
  pkg/client/informers/externalversions/apps/v1alpha1/persistentpodstate.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/apps/v1alpha1/expansion_generated.go
  pkg/client/listers/apps/v1alpha1/persistentpodstate.go
  pkg/controller/controllers.go
  pkg/controller/persistentpodstate/persistent_pod_state_controller.go
  pkg/controller/persistentpodstate/persistent_pod_state_controller_test.go
  pkg/controller/persistentpodstate/persistent_pod_state_event_handler.go
  pkg/util/controllerfinder/controller_finder.go
  pkg/util/controllerfinder/pods_finder.go
  pkg/util/tools.go
  pkg/webhook/add_persistentpodstate.go
  pkg/webhook/persistentpodstate/validating/persistent_create_update_handler.go
  pkg/webhook/persistentpodstate/validating/persistent_validating_test.go
  pkg/webhook/persistentpodstate/validating/webhooks.go
  pkg/webhook/pod/mutating/persistent_pod_state.go
  pkg/webhook/pod/mutating/persistent_pod_state_test.go
  pkg/webhook/pod/mutating/pod_create_update_handler.go
  test/e2e/apps/persistent_pod_state.go
  test/e2e/framework/persistent_pod_state_util.go
  test/e2e/framework/test_context.go
Labels: lgtm, approved, size/XXL

#980 Mark pod not ready quickly when add not ready key
  pkg/util/inplaceupdate/inplace_update.go
  pkg/util/podreadiness/pod_readiness_utils.go
  pkg/util/pods.go
Labels: lgtm, approved, size/L

#960 PersistentStatePodState proposal
  docs/img/persistent-pod-state.png
  docs/proposals/20220421-persistent-pod-state.md
Labels: lgtm, approved, size/L

#952 optmize the logic of listNamespacesForDistributor func
  pkg/controller/resourcedistribution/utils.go
Labels: lgtm, approved, size/S

#937 sidecarset forbid updating of sidecar container name
  pkg/webhook/sidecarset/validating/sidecarset_create_update_handler.go
Labels: lgtm, approved, size/XS

#982 pub support custom workload
  apis/policy/v1alpha1/podunavailablebudget_types.go
  config/rbac/role.yaml
  main.go
  pkg/control/pubcontrol/api.go
  pkg/control/pubcontrol/utils.go
  pkg/controller/cloneset/sync/api.go
  pkg/controller/cloneset/sync/cloneset_update_test.go
  pkg/controller/persistentpodstate/persistent_pod_state_controller.go
  pkg/controller/persistentpodstate/persistent_pod_state_controller_test.go
  pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
  pkg/controller/podunavailablebudget/pub_controller_test.go
  pkg/controller/podunavailablebudget/pub_pod_event_handler.go
  pkg/controller/workloadspread/reschedule_test.go
  pkg/controller/workloadspread/workloadspread_controller.go
  pkg/controller/workloadspread/workloadspread_controller_test.go
  pkg/util/controllerfinder/controller_finder.go
  pkg/util/controllerfinder/pods_finder.go
  pkg/webhook/pod/mutating/pod_create_update_handler.go
  pkg/webhook/pod/mutating/pod_unavailable_budget.go
  pkg/webhook/pod/validating/pod_create_update_handler.go
  pkg/webhook/pod/validating/pod_unavailable_budget.go
  pkg/webhook/pod/validating/pod_unavailable_budget_test.go
  pkg/webhook/podunavailablebudget/validating/pub_create_update_handler.go
  pkg/webhook/podunavailablebudget/validating/pub_validating_test.go
  test/e2e/apps/daemonset.go
Labels: lgtm, approved, size/L

#983 chore: remove some commented code and simplify some
  cmd/daemon/main.go
  pkg/webhook/cloneset/mutating/cloneset_create_update_handler.go
  pkg/webhook/server.go
  pkg/webhook/util/configuration/configuration.go
  pkg/webhook/util/controller/webhook_controller.go
  pkg/webhook/util/crd/crd.go
  pkg/webhook/util/generator/selfsigned.go
  pkg/webhook/util/generator/util.go
  pkg/webhook/util/health/checker.go
  pkg/webhook/util/writer/certwriter.go
  pkg/webhook/util/writer/fs.go
  pkg/webhook/util/writer/secret.go
Labels: lgtm, approved, size/L
