Repository openkruise/kruise, pull requests merged in 2022-09, with the labels that each got.

#1074 Reduce update pod condition operations
  pkg/util/inplaceupdate/inplace_update.go
Labels: lgtm, approved, size/S

#1073 pod probe marker apis
  apis/apps/v1alpha1/node_pod_probe_types.go
  apis/apps/v1alpha1/pod_probe_marker_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_nodepodprobes.yaml
  config/crd/bases/apps.kruise.io_podprobemarkers.yaml
  pkg/client/clientset/versioned/typed/apps/v1alpha1/apps_client.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/fake/fake_apps_client.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/fake/fake_nodepodprobe.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/fake/fake_podprobemarker.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/nodepodprobe.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/podprobemarker.go
  pkg/client/informers/externalversions/apps/v1alpha1/interface.go
  pkg/client/informers/externalversions/apps/v1alpha1/nodepodprobe.go
  pkg/client/informers/externalversions/apps/v1alpha1/podprobemarker.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/apps/v1alpha1/expansion_generated.go
  pkg/client/listers/apps/v1alpha1/nodepodprobe.go
  pkg/client/listers/apps/v1alpha1/podprobemarker.go
  pkg/controller/statefulset/stateful_set_control.go
Labels: lgtm, approved, size/XXL

#1075 pod probe marker controller
  apis/apps/v1alpha1/node_pod_probe_types.go
  config/crd/bases/apps.kruise.io_nodepodprobes.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  pkg/controller/controllers.go
  pkg/controller/nodeimage/nodeimage_event_handler.go
  pkg/controller/nodepodprobe/node_pod_probe_controller.go
  pkg/controller/nodepodprobe/node_pod_probe_controller_test.go
  pkg/controller/nodepodprobe/nodepodprobe_event_handler.go
  pkg/controller/podprobemarker/pod_probe_marker_controller.go
  pkg/controller/podprobemarker/pod_probe_marker_controller_test.go
  pkg/controller/podprobemarker/podprobemarker_event_handler.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/util/finalizer.go
  test/e2e/apps/sidecarset.go
Labels: lgtm, approved, size/XXL

#1083 WorkloadSpread consider whether patch field is matched when assign existing pods to subset
  pkg/controller/workloadspread/workloadspread_controller.go
  pkg/controller/workloadspread/workloadspread_controller_test.go
  pkg/controller/workloadspread/workloadspread_controller_utils.go
  pkg/controller/workloadspread/workloadspread_controller_utils_test.go
Labels: lgtm, approved, size/L

#1078 pod probe marker webhook
  apis/apps/v1alpha1/pod_probe_marker_types.go
  config/crd/bases/apps.kruise.io_podprobemarkers.yaml
  config/webhook/manifests.yaml
  pkg/controller/nodepodprobe/node_pod_probe_controller.go
  pkg/controller/nodepodprobe/node_pod_probe_controller_test.go
  pkg/controller/podprobemarker/pod_probe_marker_controller_test.go
  pkg/webhook/add_podprobemarker.go
  pkg/webhook/podprobemarker/validating/probe_create_update_handler.go
  pkg/webhook/podprobemarker/validating/probe_validating_test.go
  pkg/webhook/podprobemarker/validating/webhooks.go
  test/e2e/policy/podunavailablebudget.go
Labels: lgtm, approved, size/XL

#1053 pod probe marker proposal
  docs/proposals/20220728-pod-probe-marker.md
Labels: lgtm, approved, size/L

#1077 node pod probe daemon
  .github/workflows/ci.yaml
  .github/workflows/e2e-1.16.yaml
  .github/workflows/e2e-1.24.yaml
  CONTRIBUTING.md
  Dockerfile
  Dockerfile_multiarch
  Makefile
  config/rbac/daemon_role.yaml
  go.mod
  pkg/controller/nodepodprobe/node_pod_probe_controller.go
  pkg/controller/nodepodprobe/nodepodprobe_event_handler.go
  pkg/controller/podprobemarker/pod_probe_marker_controller.go
  pkg/daemon/daemon.go
  pkg/daemon/podprobe/pod_probe_controller.go
  pkg/daemon/podprobe/pod_probe_controller_test.go
  pkg/daemon/podprobe/prober.go
  pkg/daemon/podprobe/results_manager.go
  pkg/daemon/podprobe/worker.go
  pkg/features/kruise_features.go
  test/e2e/apps/podprobemarker.go
  test/e2e/framework/pod_probe_marker_util.go
Labels: lgtm, approved, size/XXL

#993 sidecarset support patch pod metadata proposal
  docs/proposals/20220615-sidecarset-patch-pod-metadata.md
Labels: lgtm, approved, size/L

#1057 Support predownload image in ads
  pkg/controller/daemonset/daemonset_controller.go
  pkg/controller/daemonset/daemonset_predownload_image.go
  pkg/controller/statefulset/statefulset_predownload_image.go
Labels: lgtm, approved, size/L

#1093 Add PreDownloadImageForDaemonSetUpdate featureGate
  pkg/controller/daemonset/daemonset_controller.go
  pkg/features/kruise_features.go
Labels: lgtm, approved, size/XS

#1092 Add changelog for v1.3.0
  CHANGELOG.md
Labels: lgtm, approved, size/M
