Repository openkruise/kruise, pull requests merged in 2022-08, with the labels that each got.

#1041 fix pub e2e failed
  pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
  pkg/controller/podunavailablebudget/pub_controller_test.go
  test/e2e/framework/podunavailablebudget_util.go
  test/e2e/policy/podunavailablebudget.go
Labels: lgtm, approved, size/M

#1046 Remove pod name label from CRR
  apis/apps/v1alpha1/containerrecreaterequest_types.go
  pkg/controller/containerrecreaterequest/crr_event_handler.go
  pkg/daemon/containerrecreate/crr_daemon_controller.go
  pkg/daemon/containerrecreate/crr_daemon_util.go
  pkg/webhook/containerrecreaterequest/mutating/crr_mutating_handler.go
  test/e2e/apps/containerrecreate.go
Labels: lgtm, approved, size/M

#1040 Bump e2e v1.23 to v1.24
  .github/workflows/ci.yaml
  .github/workflows/e2e-1.16.yaml
  .github/workflows/e2e-1.24.yaml
  test/e2e/apps/workloadspread.go
  test/e2e/framework/util.go
Labels: lgtm, approved, size/L

#1047 Consider subsets maxReplicas when workloadSpread manage existing pods .
  pkg/controller/workloadspread/workloadspread_controller.go
  pkg/controller/workloadspread/workloadspread_controller_test.go
Labels: lgtm, approved, size/M

#1054 fix sidecarset hot upgrade reset empty container bug
  pkg/control/sidecarcontrol/sidecarset_control.go
  pkg/control/sidecarcontrol/util.go
  pkg/control/sidecarcontrol/util_test.go
  pkg/controller/sidecarset/sidecarset_pod_event_handler_test.go
  pkg/controller/sidecarset/sidecarset_processor.go
  pkg/controller/sidecarset/sidecarset_strategy_test.go
  pkg/webhook/pod/mutating/sidecarset.go
Labels: lgtm, approved, size/L

#1056 Workloadspread support statefulset
  pkg/controller/workloadspread/update_pod_deletion_cost.go
  pkg/controller/workloadspread/workloadspread_controller.go
  pkg/controller/workloadspread/workloadspread_event_handler.go
  pkg/controller/workloadspread/workloadspread_event_handler_test.go
  pkg/util/workloadspread/workloadspread.go
  pkg/util/workloadspread/workloadspread_test.go
  pkg/webhook/workloadspread/validating/workloadspread_validation.go
  pkg/webhook/workloadspread/validating/workloadspread_validation_test.go
  test/e2e/apps/workloadspread.go
  test/e2e/framework/workloadspread_util.go
Labels: lgtm, approved, size/XXL

#1059 Store historical patchPodMetadata field for SidecarSet
  pkg/control/sidecarcontrol/history_control.go
  pkg/webhook/pod/mutating/sidecarset.go
  test/e2e/apps/sidecarset.go
  test/e2e/policy/podunavailablebudget.go
Labels: lgtm, approved, size/M

#1060 Update codecov-action to v3
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/XS

#1066 Performance optimization for workloadSpread when suitable subset maxReplicas is niil
  pkg/util/workloadspread/workloadspread.go
  pkg/util/workloadspread/workloadspread_test.go
Labels: lgtm, approved, size/S

#1068 Optimize performance of LabelSelector conversion
  pkg/control/pubcontrol/pub_control.go
  pkg/control/sidecarcontrol/history_control.go
  pkg/control/sidecarcontrol/util.go
  pkg/controller/cloneset/cloneset_controller.go
  pkg/controller/daemonset/daemonset_controller.go
  pkg/controller/daemonset/daemonset_event_handler.go
  pkg/controller/daemonset/daemonset_history.go
  pkg/controller/daemonset/daemonset_update.go
  pkg/controller/daemonset/daemonset_util.go
  pkg/controller/ephemeraljob/ephemeraljob_controller.go
  pkg/controller/ephemeraljob/ephemeraljob_utils.go
  pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
  pkg/controller/podunavailablebudget/pub_pod_event_handler.go
  pkg/controller/resourcedistribution/utils.go
  pkg/controller/sidecarset/sidecarset_processor.go
  pkg/controller/sidecarset/sidecarset_strategy.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/controller/workloadspread/workloadspread_controller.go
  pkg/util/controllerfinder/pods_finder.go
  pkg/util/history/controller_history_test.go
  pkg/util/imagejob/imagejob_reader.go
  pkg/util/refmanager/ref_manager.go
  pkg/util/selector.go
  pkg/util/selector_test.go
  pkg/util/updatesort/priority_sort.go
  test/e2e/framework/cloneset_util.go
  test/e2e/framework/deployment_util.go
  test/e2e/framework/resourcedistribution_utils.go
  test/e2e/framework/sidecarset_utils.go
  test/e2e/framework/workloadspread_util.go
Labels: lgtm, approved, size/L
