Repository openkruise/kruise, pull requests merged in 2022-04, with the labels that each got.

#945 add ephemeraljob e2e test in k8s1.23
  .github/workflows/ci.yaml
  .github/workflows/e2e-1.23.yaml
  test/e2e/apps/ephemeraljob.go
Labels: lgtm, approved, size/M

#954 [Feat]: Make sure at least one pod is upgraded if CloneSet Partition != 100%
  apis/apps/v1alpha1/cloneset_types.go
  config/crd/bases/apps.kruise.io_clonesets.yaml
  pkg/controller/cloneset/cloneset_predownload_image.go
  pkg/controller/cloneset/cloneset_status.go
  pkg/controller/cloneset/sync/cloneset_sync_utils.go
  pkg/controller/cloneset/sync/cloneset_sync_utils_test.go
  pkg/util/tools.go
  pkg/util/tools_test.go
  test/e2e/apps/cloneset.go
Labels: lgtm, approved, size/L

#963 Fix CloneSet status ExpectedUpdatedReplicas json name
  apis/apps/v1alpha1/cloneset_types.go
  config/crd/bases/apps.kruise.io_clonesets.yaml
Labels: lgtm, approved, size/XS
