Repository openkruise/kruise, pull requests merged in 2022-06, with the labels that each got.

#987 Fix CloneSet inconsistentStatus func ignored ExpectedUpdatedReplicas field
  pkg/controller/cloneset/cloneset_status.go
Labels: lgtm, approved, size/XS

#985 Add changelog for v1.2.0
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  CHANGELOG.md
Labels: lgtm, approved, size/M

#988 fix pub scale scheme
  pkg/util/controllerfinder/controller_finder.go
Labels: lgtm, approved, size/S

#990 cleanup unmatchedSet
  pkg/controller/resourcedistribution/utils.go
Labels: lgtm, approved, size/XS

#991 reconcile err process
  pkg/controller/uniteddeployment/uniteddeployment_controller.go
Labels: lgtm, approved, size/XS

#999 Fix panic cased by statefulset pvc auto deletion
  pkg/controller/statefulset/stateful_set_utils.go
Labels: lgtm, approved, size/XS

#1002 Add switch for PersistentPodState controller
  pkg/controller/persistentpodstate/persistent_pod_state_controller.go
Labels: lgtm, approved, size/XS

#1004 pub support pod unvailable label
  apis/apps/pub/pod_unavailable_label.go
  apis/policy/v1alpha1/podunavailablebudget_types.go
  pkg/control/pubcontrol/pub_control.go
  pkg/control/pubcontrol/pub_control_test.go
  pkg/control/pubcontrol/utils.go
  pkg/control/pubcontrol/utils_test.go
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/util/pods.go
  pkg/webhook/pod/validating/pod_unavailable_budget.go
  test/e2e/policy/podunavailablebudget.go
Labels: lgtm, approved, size/XL

#1011 Optimize Advanced DaemonSet internal new pod for imitating scheduling
  pkg/controller/daemonset/daemonset_controller.go
  pkg/controller/daemonset/daemonset_util.go
Labels: lgtm, approved, size/M
