Repository openkruise/kruise, pull requests merged in 2022-07, with the labels that each got.

#1014 Fix DaemonSet surging with minReadySeconds
  apis/apps/defaults/v1alpha1.go
  apis/apps/v1alpha1/daemonset_types.go
  config/crd/bases/apps.kruise.io_daemonsets.yaml
  pkg/controller/daemonset/daemonset_controller.go
  pkg/controller/daemonset/daemonset_util.go
  test/e2e/apps/daemonset.go
  test/e2e/framework/daemonset_util.go
Labels: lgtm, approved, size/L

#1015 Reduce kruise-manager memory allocation
  main.go
  pkg/controller/advancedcronjob/advancedcronjob_controller.go
  pkg/controller/broadcastjob/broadcastjob_controller.go
  pkg/controller/cloneset/cloneset_controller.go
  pkg/controller/cloneset/cloneset_controller_test.go
  pkg/controller/containerlaunchpriority/container_launch_priority_controller.go
  pkg/controller/containerrecreaterequest/crr_controller.go
  pkg/controller/daemonset/daemonset_controller.go
  pkg/controller/ephemeraljob/ephemeraljob_controller.go
  pkg/controller/imagepulljob/imagepulljob_controller.go
  pkg/controller/nodeimage/nodeimage_controller.go
  pkg/controller/persistentpodstate/persistent_pod_state_controller.go
  pkg/controller/podreadiness/pod_readiness_controller.go
  pkg/controller/resourcedistribution/resourcedistribution_controller.go
  pkg/controller/sidecarset/sidecarset_controller.go
  pkg/controller/statefulset/statefulset_controller.go
  pkg/controller/uniteddeployment/uniteddeployment_controller.go
  pkg/controller/uniteddeployment/uniteddeployment_controller_statefulset_test.go
  pkg/controller/uniteddeployment/uniteddeployment_controller_test.go
  pkg/controller/workloadspread/workloadspread_controller.go
  pkg/util/client/cache.go
  pkg/util/client/client.go
  pkg/util/client/delegating_client.go
  pkg/util/imagejob/imagejob_reader_test.go
  pkg/util/workloadspread/workloadspread.go
  pkg/util/workloadspread/workloadspread_test.go
  pkg/webhook/pod/mutating/container_launch_priority_initialization.go
  pkg/webhook/pod/mutating/persistent_pod_state.go
  pkg/webhook/pod/mutating/persistent_pod_state_test.go
  pkg/webhook/pod/mutating/pod_create_update_handler.go
  pkg/webhook/pod/mutating/pod_readiness.go
  pkg/webhook/pod/mutating/pod_unavailable_budget.go
  pkg/webhook/pod/mutating/sidecarset.go
  pkg/webhook/pod/mutating/sidecarset_hotupgrade_test.go
  pkg/webhook/pod/mutating/sidecarset_test.go
  pkg/webhook/pod/mutating/workloadspread.go
Labels: lgtm, approved, size/XL

#1016 fix ejob nil pointer bug
  apis/apps/v1alpha1/ephemeraljob_types.go
  config/crd/bases/apps.kruise.io_ephemeraljobs.yaml
  pkg/controller/ephemeraljob/ephemeraljob_controller.go
Labels: lgtm, approved, size/S

#1026 Optimize CloneSet queuing when cache has just synced
  pkg/controller/cloneset/cloneset_event_handler.go
Labels: lgtm, approved, size/M

#1027 Optimize event handler performance for PodUnavailableBudget
  pkg/control/pubcontrol/pub_control_utils.go
  pkg/control/pubcontrol/pub_control_utils_test.go
  pkg/controller/persistentpodstate/persistent_pod_state_event_handler.go
  pkg/controller/podunavailablebudget/pub_pod_event_handler.go
  pkg/webhook/pod/validating/pod_unavailable_budget.go
Labels: lgtm, approved, size/S

#1007 fix bug: allow optional filed maxunavilable to be nil in ads, and set default …
  pkg/controller/daemonset/daemonset_util.go
Labels: lgtm, approved, size/XS

#1024 CloneSet supports to calculate scale number excluding Pods in PreparingDelete
  apis/apps/v1alpha1/cloneset_types.go
  pkg/controller/cloneset/sync/cloneset_scale.go
  pkg/controller/cloneset/sync/cloneset_sync_utils.go
  pkg/controller/cloneset/sync/cloneset_sync_utils_test.go
  test/e2e/apps/cloneset.go
Labels: lgtm, approved, size/XL

#1030 Add release plan and process docs
  RELEASE-PROCESS.md
  RELEASES.md
Labels: lgtm, approved, size/L

#1031 Fix panic cased by asts pre-download image
  pkg/controller/statefulset/statefulset_predownload_image.go
Labels: lgtm, approved, size/XS

#1021 SidecarSet inject history revision
  apis/apps/defaults/v1alpha1.go
  apis/apps/v1alpha1/sidecarset_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_sidecarsets.yaml
  pkg/control/sidecarcontrol/hash.go
  pkg/control/sidecarcontrol/history_control.go
  pkg/control/sidecarcontrol/util.go
  pkg/controller/sidecarset/sidecarset_pod_event_handler.go
  pkg/controller/sidecarset/sidecarset_processor.go
  pkg/webhook/pod/mutating/sidecarset.go
  pkg/webhook/pod/mutating/sidecarset_test.go
  pkg/webhook/sidecarset/mutating/sidecarset_create_update_handler.go
  pkg/webhook/sidecarset/mutating/sidecarset_mutating_test.go
  pkg/webhook/sidecarset/validating/sidecarset_create_update_handler.go
  pkg/webhook/sidecarset/validating/sidecarset_validating_test.go
  test/e2e/apps/sidecarset.go
Labels: lgtm, approved, size/XL

#1036 Fix go get in Makefile with go 1.18
  Makefile
Labels: lgtm, approved, size/XS

#992 sidecarset support inject&upgrade pod annotations
  apis/apps/defaults/v1alpha1.go
  apis/apps/v1alpha1/sidecarset_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_sidecarsets.yaml
  go.mod
  main.go
  pkg/control/sidecarcontrol/hash.go
  pkg/control/sidecarcontrol/util.go
  pkg/control/sidecarcontrol/util_test.go
  pkg/controller/cloneset/cloneset_controller_test.go
  pkg/controller/sidecarset/sidecarset_processor.go
  pkg/features/kruise_features.go
  pkg/util/configuration/configuration.go
  pkg/util/configuration/types.go
  pkg/util/meta.go
  pkg/webhook/pod/mutating/sidecarset.go
  pkg/webhook/pod/mutating/sidecarset_test.go
  pkg/webhook/sidecarset/mutating/sidecarset_mutating_test.go
  pkg/webhook/sidecarset/validating/sidecarset_create_update_handler.go
  pkg/webhook/sidecarset/validating/sidecarset_validating_test.go
  pkg/webhook/util/util.go
  test/e2e/apps/sidecarset.go
  test/e2e/apps/sidecarset_hotupgrade.go
  test/e2e/framework/ephemeraljob_utils.go
  test/e2e/framework/imagepulljob_util.go
  test/e2e/framework/sidecarset_utils.go
  test/e2e/policy/podunavailablebudget.go
Labels: lgtm, approved, size/XXL

#1034 Fix doc for `BroadcastJob`
  apis/apps/v1alpha1/broadcastjob_types.go
  config/crd/bases/apps.kruise.io_advancedcronjobs.yaml
  config/crd/bases/apps.kruise.io_broadcastjobs.yaml
  config/crd/bases/apps.kruise.io_imagepulljobs.yaml
Labels: lgtm, approved, size/M

#1043 Fix expectedUpdatedReplicas logic when CloneSet rolling back
  pkg/controller/cloneset/cloneset_status.go
Labels: lgtm, approved, size/XS
