Repository openkruise/kruise, pull requests merged in 2022-12, with the labels that each got.

#1118 Allow to mutate PVCTemplate of Advanced StatefulSet & CloneSet
  pkg/webhook/cloneset/validating/validation.go
  pkg/webhook/cloneset/validating/validation_test.go
  pkg/webhook/statefulset/validating/statefulset_validation.go
  pkg/webhook/statefulset/validating/statefulset_validation_test.go
Labels: lgtm, approved, size/L

#1063 feat: add PersistentPodState custom workload support
  apis/apps/v1alpha1/persistent_pod_state_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_persistentpodstates.yaml
  docs/proposals/20220824-persistentpodstate-custom-workload-support.md
  pkg/controller/persistentpodstate/persistent_pod_state_controller.go
  pkg/controller/persistentpodstate/persistent_pod_state_event_handler.go
  pkg/controller/util/watch.go
  pkg/util/configuration/configuration.go
  pkg/util/configuration/types.go
  pkg/util/controllerfinder/controller_finder.go
  pkg/webhook/persistentpodstate/validating/persistent_create_update_handler.go
  pkg/webhook/persistentpodstate/validating/persistent_validating_test.go
  pkg/webhook/pod/mutating/persistent_pod_state.go
  test/e2e/apps/persistent_pod_state.go
  test/e2e/framework/persistent_pod_state_util.go
Labels: lgtm, approved, size/XXL

#1135 pub support get total replicas from annotations
  apis/policy/v1alpha1/podunavailablebudget_types.go
  pkg/control/pubcontrol/pub_control.go
  pkg/control/pubcontrol/pub_control_utils.go
  pkg/control/pubcontrol/pub_control_utils_test.go
  pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
  pkg/controller/podunavailablebudget/pub_controller_test.go
  pkg/controller/podunavailablebudget/pub_pod_event_handler.go
  pkg/util/controllerfinder/controller_finder.go
  pkg/util/controllerfinder/pods_finder.go
  pkg/webhook/pod/validating/pod_unavailable_budget.go
  pkg/webhook/pod/validating/pod_unavailable_budget_test.go
  pkg/webhook/podunavailablebudget/validating/pub_create_update_handler.go
  pkg/webhook/podunavailablebudget/validating/pub_validating_test.go
Labels: lgtm, approved, size/L

#1145 fix pub ut
  pkg/controller/podunavailablebudget/pub_controller_test.go
Labels: lgtm, approved, size/XS
