Repository openkruise/kruise, pull requests merged in 2023-03, with the labels that each got.

#1198 fix: fix invalid image
  config/samples/apps_v1alpha1_uniteddeployment.yaml
Labels: lgtm, approved, size/XS

#1201 Update README.md
  README-zh_CN.md
  README.md
Labels: lgtm, approved, size/S

#1203 Update README.md to announce the incubation of the project
  README-zh_CN.md
  README.md
Labels: lgtm, approved, size/XS

#1208 Update k8s registry references
  test/e2e/testing-manifests/statefulset/cassandra/tester.yaml
  test/e2e/testing-manifests/statefulset/etcd/statefulset.yaml
  test/e2e/testing-manifests/statefulset/etcd/tester.yaml
  test/e2e/testing-manifests/statefulset/mysql-galera/statefulset.yaml
  test/e2e/testing-manifests/statefulset/mysql-upgrade/tester.yaml
Labels: lgtm, approved, size/S

#1202 remove the kubebuiler validation Minimum in the types file
  apis/apps/v1alpha1/advancedcronjob_types.go
  config/crd/bases/apps.kruise.io_advancedcronjobs.yaml
  pkg/webhook/advancedcronjob/validating/advancedcronjob_create_update_handler.go
Labels: lgtm, approved, size/S

#1209 chore: simplify comparison and variable declaration
  pkg/control/sidecarcontrol/sidecarset_control.go
  pkg/controller/advancedcronjob/advancedcronjob_controller_test.go
  pkg/controller/broadcastjob/broadcastjob_controller.go
  pkg/controller/broadcastjob/broadcastjob_utils.go
  pkg/controller/cloneset/cloneset_predownload_image.go
  pkg/controller/persistentpodstate/persistent_pod_state_controller.go
  pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
  pkg/controller/sidecarset/sidecarset_hotupgrade.go
  pkg/controller/workloadspread/workloadspread_controller.go
  pkg/webhook/resourcedistribution/validating/resourcedistribution_create_update_handler.go
Labels: lgtm, approved, size/M

#1190 support attach metadata in PullImage CRI interface
  apis/apps/v1alpha1/imagepulljob_types.go
  apis/apps/v1alpha1/nodeimage_types.go
  apis/apps/v1alpha1/sandboxconfig_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_imagepulljobs.yaml
  config/crd/bases/apps.kruise.io_nodeimages.yaml
  pkg/controller/imagepulljob/imagepulljob_controller.go
  pkg/daemon/criruntime/factory.go
  pkg/daemon/criruntime/imageruntime/containerd.go
  pkg/daemon/criruntime/imageruntime/cri.go
  pkg/daemon/criruntime/imageruntime/docker.go
  pkg/daemon/criruntime/imageruntime/interface.go
  pkg/daemon/criruntime/imageruntime/pouch.go
  pkg/daemon/imagepuller/imagepuller_worker.go
Labels: lgtm, approved, size/L

#1219 Optimize CloneSet event handler codes
  pkg/controller/cloneset/cloneset_event_handler.go
  pkg/controller/cloneset/core/api.go
  pkg/controller/cloneset/core/cloneset_core.go
Labels: lgtm, approved, size/L

#1214 open partial feature-gates by default
  pkg/features/kruise_features.go
Labels: lgtm, approved, size/S

#1182 support fix containerrecreaterequest
  apis/apps/v1alpha1/containerrecreaterequest_types.go
  config/crd/bases/apps.kruise.io_containerrecreaterequests.yaml
  pkg/daemon/containerrecreate/crr_daemon_controller.go
  pkg/daemon/containerrecreate/crr_daemon_util.go
  test/e2e/apps/containerrecreate.go
  test/e2e/apps/ephemeraljob.go
Labels: lgtm, approved, size/L

#1224 Use force kill strategy of CRR in sidecar terminator controller
  pkg/controller/cloneset/cloneset_event_handler_test.go
  pkg/controller/sidecarterminator/kill_container_action.go
  pkg/controller/sidecarterminator/sidecar_terminator_controller_test.go
Labels: lgtm, approved, size/S

#1225 add changelog for v1.4.0
  CHANGELOG.md
Labels: lgtm, approved, size/M

#1149 Make OnFailure as default restartPolicy for BroadcastJob
  apis/apps/defaults/v1alpha1.go
Labels: lgtm, approved, size/XS

#1204 fix: bcj doesn't make pod on node that has erased taint
  pkg/controller/broadcastjob/broadcastjob_controller.go
  pkg/controller/broadcastjob/broadcastjob_event_handler.go
Labels: lgtm, approved, size/M

#1232 Connecting to Pouch runtime via CRI interface
  pkg/daemon/criruntime/factory.go
Labels: lgtm, approved, size/XS

#1229 fix: initContainers shareVolumePolicy is not effective
  pkg/webhook/pod/mutating/sidecarset.go
  pkg/webhook/pod/mutating/sidecarset_test.go
Labels: lgtm, approved, size/M

#1238 Fix: serviceAccountToken volume error in sidecarset
  pkg/webhook/sidecarset/validating/sidecarset_create_update_handler.go
  pkg/webhook/sidecarset/validating/sidecarset_validating_test.go
Labels: lgtm, approved, size/S
