Repository openkruise/kruise, pull requests merged in 2023-07, with the labels that each got.

#1325 feat: SidecarSet updateStrategy support priorityStrategy
  apis/apps/v1alpha1/sidecarset_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_sidecarsets.yaml
  pkg/controller/sidecarset/sidecarset_strategy.go
  pkg/controller/sidecarset/sidecarset_strategy_test.go
  pkg/webhook/sidecarset/validating/sidecarset_create_update_handler.go
Labels: lgtm, approved, size/L

#1324 cloneset ignore maxSurge when UpdateStrategyPaused=true
  pkg/controller/cloneset/sync/cloneset_sync_utils.go
  pkg/controller/cloneset/sync/cloneset_sync_utils_test.go
Labels: lgtm, approved, size/M

#1254 Add proposal for ImageListPullJob
  docs/img/ImageListPullJob.png
  docs/proposals/20230323-imagelistpulljob.md
Labels: lgtm, approved, size/L

#1317 adding updatedAvailableReplicas field
  apis/apps/v1alpha1/cloneset_types.go
  apis/apps/v1beta1/statefulset_types.go
  config/crd/bases/apps.kruise.io_clonesets.yaml
  config/crd/bases/apps.kruise.io_statefulsets.yaml
  pkg/controller/cloneset/cloneset_status.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/controller/statefulset/stateful_set_control_test.go
Labels: lgtm, approved, size/M

#1309 add condition and event info for not upgradable pods when update sidecarset (#1272)
  pkg/control/sidecarcontrol/util.go
  pkg/controller/sidecarset/sidecarset_processor.go
  pkg/controller/sidecarset/sidecarset_strategy.go
  pkg/controller/sidecarset/sidecarset_strategy_test.go
  pkg/controller/util/pod_condition_utils.go
  test/e2e/apps/sidecarset.go
Labels: lgtm, approved, size/L

#1329 support parameter set CacheSyncTimeout for controller
  main.go
  pkg/controller/advancedcronjob/advancedcronjob_controller.go
  pkg/controller/broadcastjob/broadcastjob_controller.go
  pkg/controller/cloneset/cloneset_controller.go
  pkg/controller/containerlaunchpriority/container_launch_priority_controller.go
  pkg/controller/containerrecreaterequest/crr_controller.go
  pkg/controller/daemonset/daemonset_controller.go
  pkg/controller/ephemeraljob/ephemeraljob_controller.go
  pkg/controller/imagelistpulljob/imagelistpulljob_controller.go
  pkg/controller/imagepulljob/imagepulljob_controller.go
  pkg/controller/nodeimage/nodeimage_controller.go
  pkg/controller/nodepodprobe/node_pod_probe_controller.go
  pkg/controller/persistentpodstate/persistent_pod_state_controller.go
  pkg/controller/podprobemarker/pod_probe_marker_controller.go
  pkg/controller/podreadiness/pod_readiness_controller.go
  pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
  pkg/controller/resourcedistribution/resourcedistribution_controller.go
  pkg/controller/sidecarset/sidecarset_controller.go
  pkg/controller/sidecarterminator/sidecar_terminator_controller.go
  pkg/controller/statefulset/statefulset_controller.go
  pkg/controller/uniteddeployment/uniteddeployment_controller.go
  pkg/controller/workloadspread/workloadspread_controller.go
  pkg/util/cache.go
Labels: lgtm, approved, size/M

#1334 optimize webhook patchResponse function
  pkg/webhook/pod/mutating/pod_create_update_handler.go
Labels: lgtm, approved, size/XS

#1343 enhancement: ambiguous function name of isSidecarSetNotUpdate
  pkg/controller/sidecarset/sidecarset_processor.go
Labels: lgtm, approved, size/XS

#1350 veophi apply to become an owner of Kruise
  OWNERS
Labels: lgtm, approved, size/XS
