Repository openkruise/kruise, pull requests merged in 2023-06, with the labels that each got.

#1301 fix: SidecarSet Expectations Leakage Bug
  pkg/control/sidecarcontrol/util.go
  pkg/controller/sidecarset/sidecarset_controller.go
  pkg/controller/sidecarset/sidecarset_controller_test.go
  pkg/controller/sidecarset/sidecarset_hotupgrade_test.go
  pkg/controller/sidecarset/sidecarset_pod_event_handler.go
  pkg/controller/sidecarset/sidecarset_processor.go
  pkg/controller/sidecarset/sidecarset_processor_test.go
Labels: lgtm, approved, size/L

#1304 fix: modify the ginkgo.By name of pvc deletion protection e2e
  test/e2e/policy/deletionprotection.go
Labels: lgtm, approved, size/XS

#1266 Add patch for UnitedDeployment
  apis/apps/v1alpha1/uniteddeployment_types.go
  apis/apps/v1alpha1/well_known_labels.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_uniteddeployments.yaml
  pkg/controller/uniteddeployment/adapter/advanced_statefulset_adapter.go
  pkg/controller/uniteddeployment/adapter/cloneset_adapter.go
  pkg/controller/uniteddeployment/adapter/deployment_adapter.go
  pkg/controller/uniteddeployment/adapter/statefulset_adapter.go
  pkg/controller/uniteddeployment/subset.go
  pkg/controller/uniteddeployment/uniteddeployment_controller.go
  pkg/controller/uniteddeployment/uniteddeployment_controller_advancedstatefulset_test.go
  pkg/controller/uniteddeployment/uniteddeployment_controller_cloneset_test.go
  pkg/controller/uniteddeployment/uniteddeployment_controller_deployment_test.go
  pkg/controller/uniteddeployment/uniteddeployment_controller_statefulset_test.go
  pkg/controller/uniteddeployment/uniteddeployment_update.go
Labels: lgtm, approved, size/XL

#1237 Add validation for the WorkloadSpreadSubset patch field
  pkg/webhook/util/convertor/util.go
  pkg/webhook/workloadspread/validating/workloadspread_validation.go
Labels: lgtm, approved, size/M

#1311 adding unit test for hash
  pkg/control/sidecarcontrol/hash_test.go
Labels: lgtm, approved, size/M

#1247 feat: Optimize UnitedDeployment replicas settings
  apis/apps/defaults/v1alpha1.go
  pkg/controller/uniteddeployment/allocator.go
  pkg/controller/uniteddeployment/allocator_test.go
  pkg/controller/uniteddeployment/uniteddeployment_controller_utils.go
  pkg/webhook/uniteddeployment/validating/uniteddeployment_validation.go
  pkg/webhook/uniteddeployment/validating/uniteddeployment_validation_test.go
Labels: lgtm, approved, size/L

#1314 add status.labelSelector field to unitedDeployment to support scale sub-resource
  apis/apps/v1alpha1/uniteddeployment_types.go
  config/crd/bases/apps.kruise.io_uniteddeployments.yaml
  pkg/controller/uniteddeployment/uniteddeployment_controller.go
Labels: lgtm, approved, size/M

#1316 feat: Support run e2e test casese in local
  Makefile
  tools/hack/create-cluster.sh
  tools/hack/install-kruise.sh
  tools/hack/kind-load-image.sh
  tools/hack/run-kruise-e2e-test.sh
  tools/src/kind/go.mod
  tools/src/kind/go.sum
  tools/src/kind/pin.go
  tools/tools.mk
Labels: lgtm, approved, size/L

#1290 Regard the pod at preparing update state as update revision when scaling
  pkg/controller/cloneset/sync/cloneset_scale.go
  pkg/controller/cloneset/sync/cloneset_sync_utils.go
  pkg/controller/cloneset/sync/cloneset_sync_utils_test.go
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/controller/cloneset/sync/cloneset_update_test.go
  pkg/controller/cloneset/utils/cloneset_utils.go
  pkg/controller/statefulset/stateful_set_utils.go
  pkg/controller/statefulset/stateful_update_utils.go
  pkg/controller/statefulset/stateful_update_utils_test.go
  pkg/features/kruise_features.go
  pkg/util/revision/revision.go
  pkg/util/revision/revision_test.go
  test/e2e/apps/cloneset.go
  test/e2e/framework/cloneset_util.go
Labels: lgtm, approved, size/XL
