Repository openkruise/kruise, pull requests merged in 2023-12, with the labels that each got.

#1464 [Fix] ResourceDistribution should watch unstructured object
  pkg/controller/resourcedistribution/resourcedistribution_controller.go
  test/e2e/apps/imagelistpulljobs.go
Labels: lgtm, approved, size/M

#1462 fix: find workload spec.replicas
  pkg/util/controllerfinder/controller_finder.go
  pkg/util/controllerfinder/controller_finder_test.go
Labels: lgtm, approved, size/M

#1457 fix no test cases actually run in controller_revision_test file
  pkg/controller/cloneset/revision/cloneset_revision_test.go
Labels: lgtm, approved, size/XS, ok-to-test

#1197 WorkloadSpread support workload rolling update case
  apis/apps/v1alpha1/workloadspread_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_workloadspreads.yaml
  pkg/controller/workloadspread/update_pod_deletion_cost.go
  pkg/controller/workloadspread/workloadspread_controller.go
  pkg/controller/workloadspread/workloadspread_controller_test.go
  pkg/controller/workloadspread/workloadspread_event_handler.go
  pkg/controller/workloadspread/workloadspread_event_handler_test.go
  pkg/util/tools.go
  pkg/util/workloadspread/workloadspread.go
  pkg/util/workloadspread/workloadspread_test.go
  test/e2e/apps/workloadspread.go
Labels: lgtm, approved, size/XXL
