Repository openkruise/kruise, pull requests merged in 2023-08, with the labels that each got.

#1355 Fix tools/kind are lost
  Makefile
Labels: lgtm, approved, size/XS

#1348 [enhancement] fix comment error for function isJobFailed of broadcastjob
  pkg/controller/broadcastjob/broadcastjob_controller.go
Labels: lgtm, approved, size/XS

#1358 CloneSet watch the changes to pods' ownerRef
  pkg/controller/cloneset/cloneset_event_handler.go
Labels: lgtm, approved, size/XS

#1357 add imagepulljob featuregate
  pkg/controller/imagelistpulljob/imagelistpulljob_controller.go
  pkg/controller/imagepulljob/imagepulljob_controller.go
  pkg/features/kruise_features.go
  pkg/webhook/imagelistpulljob/validating/imagelistpulljob_create_update_handler.go
  pkg/webhook/imagepulljob/validating/imagepulljob_create_update_handler.go
  test/e2e/apps/pullimages.go
Labels: lgtm, approved, size/M

#1360 add resourcesdistribution featuregate
  config/rbac/role.yaml
  pkg/controller/resourcedistribution/resourcedistribution_controller.go
  pkg/features/kruise_features.go
  pkg/webhook/resourcedistribution/validating/resourcedistribution_create_update_handler.go
  pkg/webhook/server.go
Labels: lgtm, approved, size/M

#1367 chore: update envtest Makefile job
  Makefile
  config/crd/bases/apps.kruise.io_advancedcronjobs.yaml
  config/crd/bases/apps.kruise.io_broadcastjobs.yaml
  config/crd/bases/apps.kruise.io_clonesets.yaml
  config/crd/bases/apps.kruise.io_containerrecreaterequests.yaml
  config/crd/bases/apps.kruise.io_daemonsets.yaml
  config/crd/bases/apps.kruise.io_ephemeraljobs.yaml
  config/crd/bases/apps.kruise.io_imagelistpulljobs.yaml
  config/crd/bases/apps.kruise.io_imagepulljobs.yaml
  config/crd/bases/apps.kruise.io_nodeimages.yaml
  config/crd/bases/apps.kruise.io_nodepodprobes.yaml
  config/crd/bases/apps.kruise.io_persistentpodstates.yaml
  config/crd/bases/apps.kruise.io_podprobemarkers.yaml
  config/crd/bases/apps.kruise.io_resourcedistributions.yaml
  config/crd/bases/apps.kruise.io_sidecarsets.yaml
  config/crd/bases/apps.kruise.io_statefulsets.yaml
  config/crd/bases/apps.kruise.io_uniteddeployments.yaml
  config/crd/bases/apps.kruise.io_workloadspreads.yaml
  config/crd/bases/policy.kruise.io_podunavailablebudgets.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  scripts/setup-envtest.sh
Labels: lgtm, approved, size/L

#1370 change version of controller-runtime to v0.12.3
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/.golangci.yml
  vendor/sigs.k8s.io/controller-runtime/FAQ.md
  vendor/sigs.k8s.io/controller-runtime/OWNERS_ALIASES
  vendor/sigs.k8s.io/controller-runtime/README.md
  vendor/sigs.k8s.io/controller-runtime/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/deleg_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/transformers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/certwatcher/certwatcher.go
  vendor/sigs.k8s.io/controller-runtime/pkg/certwatcher/metrics/metrics.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/metadata_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/namespaced_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/watch.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/crd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/flock_unix.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/addr/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/certs/tinyca.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/apiserver.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/auth.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/etcd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/plane.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/process.go
  vendor/sigs.k8s.io/controller-runtime/pkg/leaderelection/leader_election.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/warning_handler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/runnable_group.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/signals/signal_posix.go
  vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/defaulter_custom.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator_custom.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
Labels: lgtm, approved, size/XL

#1361 Add 1.5.0 change log
  CHANGELOG.md
Labels: lgtm, approved, size/M

#1365 add DeletionProtectionForCRDCascadingGate
  pkg/features/kruise_features.go
  pkg/webhook/util/deletionprotection/deletion_protection.go
Labels: lgtm, approved, size/S

#1372 update 1.5.0 changeLog
  CHANGELOG.md
Labels: lgtm, approved, size/XS

#1373 [Enhance] Use utilruntime.Must enhanced check
  Makefile
  main.go
  pkg/control/pubcontrol/pub_control_utils_test.go
  pkg/control/sidecarcontrol/util_test.go
  pkg/controller/advancedcronjob/advancedcronjob_controller_test.go
  pkg/controller/broadcastjob/broadcastjob_controller_suite_test.go
  pkg/controller/broadcastjob/broadcastjob_controller_test.go
  pkg/controller/cloneset/cloneset_controller_suite_test.go
  pkg/controller/cloneset/revision/cloneset_revision_test.go
  pkg/controller/cloneset/sync/cloneset_update_test.go
  pkg/controller/daemonset/daemonset_controller_test.go
  pkg/controller/imagelistpulljob/imagelistpulljob_controller_test.go
  pkg/controller/nodepodprobe/node_pod_probe_controller_test.go
  pkg/controller/persistentpodstate/persistent_pod_state_controller_test.go
  pkg/controller/podprobemarker/pod_probe_marker_controller_test.go
  pkg/controller/podunavailablebudget/pub_controller_test.go
  pkg/controller/sidecarset/sidecarset_controller_test.go
  pkg/controller/sidecarterminator/sidecar_terminator_controller_test.go
  pkg/controller/statefulset/statefulset_controller_suite_test.go
  pkg/controller/uniteddeployment/uniteddeployment_controller_suite_test.go
  pkg/controller/workloadspread/workloadspread_controller_test.go
  pkg/daemon/daemon.go
  pkg/util/discovery/discovery.go
  pkg/util/imagejob/imagejob_reader_test.go
  pkg/util/workloadspread/workloadspread_test.go
  pkg/webhook/broadcastjob/mutating/broadcastjob_create_update_handler_test.go
  pkg/webhook/persistentpodstate/validating/persistent_validating_test.go
  pkg/webhook/pod/mutating/sidecarset_test.go
  pkg/webhook/pod/validating/pod_unavailable_budget_test.go
  pkg/webhook/podprobemarker/validating/probe_validating_test.go
  pkg/webhook/podunavailablebudget/validating/pub_validating_test.go
  pkg/webhook/sidecarset/validating/sidecarset_validating_test.go
  pkg/webhook/util/crd/crd.go
  pkg/webhook/workloadspread/validating/workloadspread_validation_test.go
  test/e2e/apps/persistent_pod_state.go
  test/e2e/e2e_test.go
  test/e2e/framework/persistent_pod_state_util.go
  tools/src/kind/pin.go
Labels: lgtm, approved, size/L

#1390 set clonesets updatedAvailableReplicas omitempty
  apis/apps/v1alpha1/cloneset_types.go
  config/crd/bases/apps.kruise.io_clonesets.yaml
Labels: lgtm, approved, size/XS

#1382 update meeting time and links for community call
  README-zh_CN.md
  README.md
Labels: lgtm, approved, size/S

#1393 wrokflow docker image ci
  .github/workflows/docker-image.yaml
Labels: lgtm, approved, size/S
