Repository openkruise/kruise, pull requests merged in 2023-02, with the labels that each got.

#1173 add zmberg as owner
  OWNERS
Labels: lgtm, approved, size/XS

#1166 fix: update alpine base image
  Dockerfile
  Dockerfile_multiarch
  Makefile
Labels: lgtm, approved, size/M

#1157 fix pod hang in PreparingUpdate state when rollback before update hook
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/controller/statefulset/stateful_set_control.go
Labels: lgtm, approved, size/M, ok-to-test

#1170 Job Sidecar terminator proposal
  docs/img/sidecar-terminator.png
  docs/proposals/20230130-job-sidecar-terminator.md
Labels: lgtm, approved, size/M

#1164 fix the bug that pub calculates pods(deployment) totalReplicas incorrectly
  pkg/control/pubcontrol/pub_control.go
  pkg/controller/podunavailablebudget/pub_controller_test.go
  pkg/util/controllerfinder/controller_finder.go
  pkg/util/controllerfinder/pods_finder.go
  test/e2e/framework/podunavailablebudget_util.go
  test/e2e/policy/podunavailablebudget.go
Labels: lgtm, approved, size/XL

#1175 fix: replace deadcode with unused and address existing issues
  .golangci.yml
  RELEASES.md
  apis/apps/pub/update_priority.go
  config/crd/bases/apps.kruise.io_clonesets.yaml
  config/crd/bases/apps.kruise.io_statefulsets.yaml
  config/crd/bases/apps.kruise.io_uniteddeployments.yaml
  main.go
  pkg/control/sidecarcontrol/util_hotupgrade.go
  pkg/controller/daemonset/daemonset_controller.go
  pkg/controller/daemonset/daemonset_predownload_image.go
  pkg/controller/daemonset/daemonset_util.go
  pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
  pkg/controller/statefulset/stateful_set_control_test.go
  pkg/controller/statefulset/statefulset_controller.go
  pkg/controller/workloadspread/reschedule_test.go
  pkg/controller/workloadspread/update_pod_deletion_cost.go
  pkg/daemon/criruntime/imageruntime/helpers.go
  pkg/daemon/imagepuller/utils.go
  pkg/daemon/util/util.go
  pkg/util/selector.go
  pkg/util/tools.go
  pkg/webhook/advancedcronjob/validating/advancedcronjob_create_update_handler.go
  pkg/webhook/util/writer/atomic/atomic_writer.go
  pkg/webhook/workloadspread/validating/workloadspread_validation_test.go
Labels: lgtm, approved, size/L

#1185 feat: add typos to GitHub action
  .github/workflows/ci.yaml
  Dockerfile
  Dockerfile_multiarch
  apis/apps/v1alpha1/nodeimage_types.go
  config/crd/bases/apps.kruise.io_nodeimages.yaml
  docs/contributing/BUMP_KUBERNETES_VERSION.md
  docs/proposals/20210316-containerrecreaterequest.md
  docs/proposals/20210614-podunavailablebudget.md
  docs/proposals/20210719-resourcedistribution.md
  pkg/control/pubcontrol/pub_control_test.go
  pkg/control/sidecarcontrol/util_hotupgrade.go
  pkg/control/sidecarcontrol/util_test.go
  pkg/controller/advancedcronjob/advancedcronjob_broadcastjob_controller.go
  pkg/controller/advancedcronjob/advancedcronjob_job_controller.go
  pkg/controller/broadcastjob/broadcastjob_controller.go
  pkg/controller/cloneset/sync/api.go
  pkg/controller/daemonset/daemonset_controller.go
  pkg/controller/daemonset/daemonset_update_test.go
  pkg/controller/sidecarset/sidecarset_strategy.go
  pkg/controller/statefulset/stateful_set_control_test.go
  pkg/controller/statefulset/stateful_set_utils_test.go
  pkg/controller/uniteddeployment/uniteddeployment_controller_advancedstatefulset_test.go
  pkg/controller/uniteddeployment/uniteddeployment_controller_cloneset_test.go
  pkg/daemon/criruntime/imageruntime/containerd.go
  test/e2e/apps/statefulset.go
  test/e2e/framework/test_context.go
  test/e2e/framework/util.go
  typos.toml
Labels: lgtm, approved, size/L

#1147 Reduce queuing frequency cased by pod update for CloneSet.
  pkg/controller/cloneset/cloneset_event_handler.go
  pkg/controller/cloneset/cloneset_event_handler_test.go
  pkg/features/kruise_features.go
Labels: kind/enhancement, lgtm, approved, size/L

#1189 [fix #1128] some rollingupdate field can not updated
  apis/apps/defaults/v1beta1.go
Labels: lgtm, approved, size/XS

#1051 Add job sidecar terminator controller
  apis/apps/v1alpha1/well_known_labels.go
  pkg/controller/controllers.go
  pkg/controller/sidecarterminator/inplace_update_action.go
  pkg/controller/sidecarterminator/kill_container_action.go
  pkg/controller/sidecarterminator/sidecar_terminator_controller.go
  pkg/controller/sidecarterminator/sidecar_terminator_controller_test.go
  pkg/controller/sidecarterminator/sidecar_terminator_pod_event_handler.go
  pkg/controller/sidecarterminator/sidecar_terminator_pod_event_handler_test.go
  pkg/controller/sidecarterminator/virtual_kubelet_manager.go
  pkg/features/kruise_features.go
  test/e2e/apps/sidecarterminator.go
Labels: kind/enhancement, lgtm, approved, size/XXL

#1193 feat: change Kruise leader election from configmap to configmapsleases
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  main.go
Labels: lgtm, approved, size/M

#1178 sidecarSet support namespace selector
  apis/apps/v1alpha1/sidecarset_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_sidecarsets.yaml
  pkg/control/sidecarcontrol/util.go
  pkg/control/sidecarcontrol/util_test.go
  pkg/controller/sidecarset/sidecarset_processor.go
  pkg/webhook/pod/mutating/sidecarset.go
  pkg/webhook/sidecarset/validating/sidecarset_create_update_handler.go
  pkg/webhook/sidecarset/validating/sidecarset_validating_test.go
  pkg/webhook/sidecarset/validating/utils.go
  test/e2e/apps/sidecarset.go
Labels: kind/enhancement, lgtm, approved, size/XL
