Repository openkruise/kruise, pull requests merged in 2023-09, with the labels that each got.

#1397 Trimming the kruise image to remove some non-essential commands
  Dockerfile
  Dockerfile_multiarch
Labels: lgtm, approved, size/S

#1401 Fix EphemeralJob event handler for deleting object
  pkg/controller/ephemeraljob/ephemeraljob_event_handler.go
Labels: lgtm, approved, size/XS

#1398 add prometheus for pub and deletion protection
  main.go
  pkg/control/pubcontrol/api.go
  pkg/control/pubcontrol/pub_control.go
  pkg/control/pubcontrol/pub_control_metrics.go
  pkg/control/pubcontrol/pub_control_utils.go
  pkg/control/pubcontrol/pub_control_utils_test.go
  pkg/controller/cloneset/sync/api.go
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/controller/cloneset/sync/cloneset_update_test.go
  pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
  pkg/controller/podunavailablebudget/pub_controller_test.go
  pkg/controller/podunavailablebudget/pub_pod_event_handler.go
  pkg/webhook/builtinworkloads/validating/builtin_handlers.go
  pkg/webhook/cloneset/validating/cloneset_create_update_handler.go
  pkg/webhook/customresourcedefinition/validating/crd_handler.go
  pkg/webhook/namespace/validating/namespace_handler.go
  pkg/webhook/pod/validating/pod_create_update_handler.go
  pkg/webhook/pod/validating/pod_unavailable_budget.go
  pkg/webhook/pod/validating/pod_unavailable_budget_test.go
  pkg/webhook/statefulset/validating/statefulset_create_update_handler.go
  pkg/webhook/uniteddeployment/validating/uniteddeployment_create_update_handler.go
  pkg/webhook/util/deletionprotection/prometheus.go
Labels: lgtm, approved, size/L

#1403 chore: unnecessary use of fmt.Sprintf
  test/e2e/apps/resourcedistribution.go
  test/e2e/apps/sidecarset.go
  test/e2e/apps/sidecarset_hotupgrade.go
  test/e2e/apps/workloadspread.go
  test/e2e/policy/podunavailablebudget.go
Labels: lgtm, approved, size/M

#1404 chore: remove refs to deprecated io/ioutil
  pkg/webhook/util/health/checker.go
  pkg/webhook/util/writer/fs.go
  test/e2e/framework/test_context.go
  test/e2e/framework/testfiles/testfiles.go
Labels: lgtm, approved, size/S

#1265 Add proposal of UnitedDeployment Patch
  docs/proposals/20230424-uniteddeployment-patch.md
Labels: lgtm, approved, size/M

#1402 update merge annotation for kruise apis
  apis/apps/v1alpha1/containerrecreaterequest_types.go
  apis/apps/v1alpha1/ephemeraljob_types.go
  apis/apps/v1alpha1/pod_probe_marker_types.go
  apis/apps/v1alpha1/resourcedistribution_types.go
  apis/apps/v1alpha1/sidecarset_types.go
  apis/apps/v1alpha1/uniteddeployment_types.go
  apis/apps/v1alpha1/workloadspread_types.go
  pkg/control/sidecarcontrol/history_control.go
  pkg/webhook/pod/mutating/sidecarset_test.go
Labels: lgtm, approved, size/M

#1416 feat: add enable pprof flag for deamon
  cmd/daemon/main.go
Labels: lgtm, approved, size/S

#1407 use "leases" by default
  main.go
Labels: lgtm, approved, size/XS

#1414 parameters defined as constants
  pkg/webhook/advancedcronjob/validating/advancedcronjob_create_update_handler.go
Labels: lgtm, approved, size/XS

#1424 fix sidecarset ExpectUpdated block upgrade container
  pkg/control/pubcontrol/pub_control.go
  pkg/control/sidecarcontrol/api.go
  pkg/control/sidecarcontrol/sidecarset_control.go
  pkg/controller/sidecarset/sidecarset_processor.go
  pkg/controller/sidecarset/sidecarset_strategy.go
  test/e2e/apps/sidecarset.go
  test/e2e/framework/sidecarset_utils.go
Labels: lgtm, approved, size/M
