Repository openkruise/kruise, pull requests merged in 2023-01, with the labels that each got.

#1151 fix go mod checksum error
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#1113 enable mcloneset deleting pvc when pod hanging
  apis/apps/v1alpha1/cloneset_types.go
  config/crd/bases/apps.kruise.io_clonesets.yaml
  config/crd/bases/apps.kruise.io_uniteddeployments.yaml
  pkg/controller/cloneset/cloneset_controller.go
  pkg/controller/cloneset/sync/cloneset_scale.go
  pkg/controller/cloneset/utils/cloneset_utils.go
  pkg/util/ownerref.go
  pkg/util/ownerref_test.go
Labels: lgtm, approved, size/L

#1136 Update stateful_set_utils.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/controller/statefulset/stateful_set_utils.go
  test/e2e/apps/statefulset.go
Labels: lgtm, approved, size/L

#1111 Add proposal for PreNormalHook
  docs/img/lifecycle-state-machine.jpg
  docs/img/prenormal-hook-seq-1.jpg
  docs/img/prenormal-hook-seq-2.jpg
  docs/proposals/20221026-pot-created-hook.md
Labels: lgtm, approved, size/M

#1158 when DisablePVCReuse=true, set cloneSet pvc owner to pod
  apis/apps/v1alpha1/cloneset_types.go
  config/crd/bases/apps.kruise.io_clonesets.yaml
  config/crd/bases/apps.kruise.io_uniteddeployments.yaml
  pkg/controller/cloneset/cloneset_controller.go
  pkg/controller/cloneset/cloneset_controller_suite_test.go
  pkg/controller/cloneset/cloneset_controller_test.go
  pkg/controller/cloneset/utils/cloneset_utils.go
  pkg/util/ownerref.go
  pkg/util/ownerref_test.go
  test/e2e/apps/cloneset.go
  test/e2e/framework/cloneset_util.go
Labels: lgtm, approved, size/XL

#1163 The log level is error, what need to be shown is indicated
  pkg/daemon/containerrecreate/crr_daemon_controller.go
Labels: lgtm, approved, size/XS
