Repository openkruise/kruise, pull requests merged in 2023-04, with the labels that each got.

#1244 disable feature-gate PreDownloadImageForInPlaceUpdate by default
  CHANGELOG.md
  README-zh_CN.md
  README.md
  pkg/features/kruise_features.go
Labels: lgtm, approved, size/S

#1235 Add missing finalizers permissions
  config/rbac/role.yaml
  pkg/controller/advancedcronjob/advancedcronjob_broadcastjob_controller.go
  pkg/controller/advancedcronjob/advancedcronjob_controller.go
  pkg/controller/broadcastjob/broadcastjob_controller.go
  pkg/controller/cloneset/cloneset_controller.go
  pkg/controller/containerrecreaterequest/crr_controller.go
  pkg/controller/daemonset/daemonset_controller.go
  pkg/controller/imagepulljob/imagepulljob_controller.go
  pkg/controller/nodeimage/nodeimage_controller.go
  pkg/controller/nodepodprobe/node_pod_probe_controller.go
  pkg/controller/persistentpodstate/persistent_pod_state_controller.go
  pkg/controller/podprobemarker/pod_probe_marker_controller.go
  pkg/controller/podunavailablebudget/podunavailablebudget_controller.go
  pkg/controller/resourcedistribution/resourcedistribution_controller.go
  pkg/controller/sidecarset/sidecarset_controller.go
  pkg/controller/statefulset/statefulset_controller.go
  pkg/controller/uniteddeployment/uniteddeployment_controller.go
  pkg/controller/workloadspread/workloadspread_controller.go
  pkg/webhook/pod/validating/pod_unavailable_budget.go
Labels: lgtm, approved, size/L

#1228 Add DeletionProtection mechanism reject Namespace deletion when PVCs are included under NS
  pkg/webhook/util/deletionprotection/deletion_protection.go
  test/e2e/policy/deletionprotection.go
Labels: lgtm, approved, size/M

#1255 Upgrade GitHub CI runner from ubuntu-18.04 to ubuntu-20.04
  .github/workflows/ci.yaml
  .github/workflows/e2e-1.16.yaml
  .github/workflows/e2e-1.20.yaml
  .github/workflows/e2e-1.24.yaml
  .github/workflows/license.yml
Labels: lgtm, approved, size/M

#1246 feat: Advanced Workload pre-download image support attach metadata in ImagePullJob
  pkg/controller/cloneset/cloneset_predownload_image.go
  pkg/controller/daemonset/daemonset_predownload_image.go
  pkg/controller/statefulset/statefulset_predownload_image.go
  pkg/util/imagejob/utilfunction/imagejob_util.go
Labels: lgtm, approved, size/S

#1258 add apis for imagelistpulljob and ImagePullJobTemplate definition
  apis/apps/v1alpha1/imagelistpulljob_types.go
  apis/apps/v1alpha1/imagepulljob_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_imagelistpulljobs.yaml
  pkg/client/clientset/versioned/typed/apps/v1alpha1/apps_client.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/fake/fake_apps_client.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/fake/fake_imagelistpulljob.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/apps/v1alpha1/imagelistpulljob.go
  pkg/client/informers/externalversions/apps/v1alpha1/imagelistpulljob.go
  pkg/client/informers/externalversions/apps/v1alpha1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/apps/v1alpha1/expansion_generated.go
  pkg/client/listers/apps/v1alpha1/imagelistpulljob.go
  pkg/util/imagejob/imagejob_reader_test.go
  pkg/util/imagejob/utilfunction/imagejob_util.go
  test/e2e/apps/pullimages.go
Labels: lgtm, approved, size/XXL

#1259 Add default annotation to sandbox-config when pulling image
  pkg/daemon/criruntime/imageruntime/cri.go
Labels: lgtm, approved, size/S
