Repository openkruise/kruise, pull requests merged in 2023-10, with the labels that each got.

#1429 [BUG] Fixed some error messages
  pkg/webhook/podprobemarker/validating/probe_create_update_handler.go
Labels: lgtm, approved, size/S

#1435 fix sidecarset upgrade exception for UpdateExpectations
  pkg/controller/sidecarset/sidecarset_pod_event_handler.go
Labels: lgtm, approved, size/XS

#1430 Reduce the number of updateNodePodProbes calls
  pkg/controller/podprobemarker/pod_probe_marker_controller.go
Labels: lgtm, approved, size/M

#1428 Add subset capacity planning for UnitedDeployment
  apis/apps/defaults/v1alpha1.go
  apis/apps/v1alpha1/uniteddeployment_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_uniteddeployments.yaml
  pkg/controller/uniteddeployment/allocator.go
  pkg/controller/uniteddeployment/allocator_test.go
  pkg/controller/uniteddeployment/uniteddeployment_controller.go
  pkg/webhook/uniteddeployment/validating/uniteddeployment_validation.go
  pkg/webhook/uniteddeployment/validating/uniteddeployment_validation_test.go
  test/e2e/apps/uniteddeployment.go
  test/e2e/framework/uniteddeployment.go
Labels: lgtm, approved, size/XL

#1438 add pub&deletion_protection audit log
  main.go
  pkg/control/pubcontrol/pub_control_utils.go
  pkg/util/logger.go
  pkg/webhook/builtinworkloads/validating/builtin_handlers.go
  pkg/webhook/cloneset/validating/cloneset_create_update_handler.go
  pkg/webhook/customresourcedefinition/validating/crd_handler.go
  pkg/webhook/namespace/validating/namespace_handler.go
  pkg/webhook/statefulset/validating/statefulset_create_update_handler.go
  pkg/webhook/uniteddeployment/validating/uniteddeployment_create_update_handler.go
Labels: lgtm, approved, size/L
