Repository openkruise/kruise, pull requests merged in 2023-05, with the labels that each got.

#1274 Fix the issue of missing Pods in pub list function
  pkg/util/controllerfinder/pods_finder.go
Labels: lgtm, approved, size/XS

#1279 Fix the issue of dependencies failing to pull in the Dockerfile.
  Dockerfile
  Dockerfile_multiarch
Labels: lgtm, approved, size/XS

#1280 update the image status when start pulling images
  pkg/daemon/criruntime/imageruntime/helpers.go
  pkg/daemon/criruntime/imageruntime/helpers_test.go
  pkg/daemon/imagepuller/imagepuller_worker.go
Labels: lgtm, approved, size/L

#1283 optimize container launch priority event handler
  pkg/controller/containerlaunchpriority/container_launch_priority_controller.go
Labels: lgtm, approved, size/XS

#1278 Merge the update requests of status and extra status for CloneSet
  pkg/controller/cloneset/cloneset_status.go
  pkg/controller/cloneset/core/api.go
  pkg/controller/cloneset/core/cloneset_core.go
Labels: lgtm, approved, size/M

#1288 Extend pull image response timeout to 10min
  pkg/controller/nodeimage/nodeimage_controller.go
  test/e2e/apps/pullimages.go
Labels: lgtm, approved, size/S

#1222 Add ImageListPullJob to simplify ImagePullJob
  .github/workflows/e2e-1.16.yaml
  .github/workflows/e2e-1.24.yaml
  apis/apps/defaults/v1alpha1.go
  apis/apps/v1alpha1/imagelistpulljob_types.go
  config/crd/bases/apps.kruise.io_imagelistpulljobs.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  pkg/controller/controllers.go
  pkg/controller/imagelistpulljob/imagelistpulljob_controller.go
  pkg/controller/imagelistpulljob/imagelistpulljob_controller_test.go
  pkg/controller/imagelistpulljob/imagelistpulljob_event_handler.go
  pkg/util/fieldindex/register.go
  pkg/webhook/add_imagelistpulljob.go
  pkg/webhook/imagelistpulljob/mutating/imagelistpulljob_create_update_handler.go
  pkg/webhook/imagelistpulljob/mutating/webhooks.go
  pkg/webhook/imagelistpulljob/validating/imagelistpulljob_create_update_handler.go
  pkg/webhook/imagelistpulljob/validating/webhooks.go
  test/e2e/apps/imagelistpulljobs.go
  test/e2e/framework/imagelistpulljob_util.go
Labels: lgtm, approved, size/XXL

#1291 Fix cloneSet extra status update logic
  pkg/controller/cloneset/cloneset_status.go
  pkg/controller/cloneset/core/api.go
  pkg/controller/cloneset/core/cloneset_core.go
Labels: lgtm, approved, size/S

#1286 WorkloadSpread support customized workload
  pkg/controller/persistentpodstate/persistent_pod_state_controller.go
  pkg/controller/persistentpodstate/persistent_pod_state_event_handler.go
  pkg/controller/util/watch.go
  pkg/controller/workloadspread/workloadspread_controller.go
  pkg/controller/workloadspread/workloadspread_event_handler.go
  pkg/util/client/client.go
  pkg/util/configuration/configuration.go
  pkg/util/configuration/types.go
  pkg/util/controllerfinder/controller_finder.go
  pkg/util/controllerfinder/pods_finder.go
  pkg/util/workloadspread/workloadspread.go
  pkg/util/workloadspread/workloadspread_test.go
  pkg/webhook/persistentpodstate/validating/persistent_create_update_handler.go
  pkg/webhook/pod/mutating/persistent_pod_state.go
  pkg/webhook/workloadspread/validating/workloadspread_validation.go
Labels: lgtm, approved, size/XL

#1294 Fix ImageListPullJob e2e
  test/e2e/apps/imagelistpulljobs.go
  test/e2e/framework/imagelistpulljob_util.go
Labels: lgtm, approved, size/M

#1300 avoid mutate controllerrevision cache in predownloadimage
  pkg/controller/cloneset/cloneset_predownload_image.go
  pkg/controller/daemonset/daemonset_predownload_image.go
  pkg/controller/sidecarset/sidecarset_processor.go
  pkg/controller/statefulset/statefulset_predownload_image.go
Labels: lgtm, approved, size/M

#1295 fix: fixed a panic: assignment to entry in nil map
  pkg/util/inplaceupdate/inplace_update_defaults.go
Labels: lgtm, approved, size/S

#1302 modify e2e deletionprotection pvc configuration
  test/e2e/policy/deletionprotection.go
Labels: lgtm, approved, size/M
