Repository openkruise/kruise, pull requests merged in 2024-09, with the labels that each got.

#1724 fix sidecarset e2e
  test/e2e/apps/sidecarset.go
Labels: lgtm, approved, size/S

#1688 fix kind install bug
  tools/src/kind/pin.go
  tools/tools.mk
Labels: lgtm, approved, size/XS

#1727 1.7.1 changelog
  CHANGELOG.md
Labels: lgtm, approved, size/XS

#1689 On pod creation, if a new pod matches the SidecarSet update strategy …
  apis/apps/v1alpha1/sidecarset_types.go
  config/crd/bases/apps.kruise.io_sidecarsets.yaml
  pkg/webhook/pod/mutating/sidecarset.go
  pkg/webhook/pod/mutating/sidecarset_test.go
  test/e2e/apps/sidecarset.go
Labels: lgtm, size/L

#1714 Auto resize pvc when only expand volumeClaimTemplates in asts
  .github/workflows/e2e-1.18.yaml
  .github/workflows/e2e-1.24.yaml
  .github/workflows/e2e-1.26.yaml
  .github/workflows/e2e-1.28.yaml
  pkg/controller/statefulset/stateful_set_control.go
  test/e2e/apps/statefulset.go
Labels: lgtm, size/L
