Repository openkruise/kruise, pull requests merged in 2024-07, with the labels that each got.

#1657 changed the scorecard badge link to the standard format
  README.md
Labels: lgtm, approved, size/XS

#1665 add support for external certs
  apis/apps/v1alpha1/daemonset_types.go
  config/crd/bases/apps.kruise.io_daemonsets.yaml
  config/manager/manager.yaml
  pkg/features/kruise_features.go
  pkg/webhook/util/configuration/configuration.go
  pkg/webhook/util/controller/webhook_controller.go
  pkg/webhook/util/crd/crd.go
  pkg/webhook/util/util.go
  pkg/webhook/util/writer/certwriter.go
  pkg/webhook/util/writer/external.go
  pkg/webhook/util/writer/external_test.go
Labels: lgtm, approved, size/L

#1667 feat: add pod index label for Advanced StatefulSet
  pkg/controller/statefulset/stateful_set_utils.go
  pkg/controller/statefulset/stateful_set_utils_test.go
  pkg/features/kruise_features.go
Labels: lgtm, approved, size/S

#1678 Fix nil panic in cloneset validating webhook
  pkg/webhook/cloneset/validating/validation.go
Labels: lgtm, approved, size/XS
