Repository openkruise/kruise, pull requests merged in 2024-03, with the labels that each got.

#1514 optimize imagepulljob code
  pkg/controller/imagepulljob/imagepulljob_utils.go
  pkg/controller/imagepulljob/imagepulljob_utils_test.go
  pkg/daemon/daemon.go
  pkg/daemon/imagepuller/imagepuller_controller.go
Labels: lgtm, approved, size/L

#1510 fix: upgrade minimum dockerapi version
  pkg/daemon/criruntime/imageruntime/docker.go
  pkg/daemon/criruntime/imageruntime/docker_test.go
Labels: lgtm, approved, size/M

#1269 add: Support the deletion protection of service and ingress
  config/webhook/manifests.yaml
  config/webhook/patch_manifests.yaml
  pkg/features/kruise_features.go
  pkg/webhook/add_ingress.go
  pkg/webhook/add_service.go
  pkg/webhook/ingress/validating/ingress_handler.go
  pkg/webhook/ingress/validating/webhooks.go
  pkg/webhook/service/validating/service_handler.go
  pkg/webhook/service/validating/webhooks.go
  pkg/webhook/util/deletionprotection/deletion_protection.go
  test/e2e/policy/deletionprotection.go
Labels: lgtm, approved, size/L

#1518 chores: use golang standard errors
  .github/workflows/ci.yaml
  .golangci.yml
  go.mod
  pkg/controller/statefulset/stateful_set_control_test.go
  pkg/daemon/criruntime/imageruntime/containerd.go
  pkg/daemon/criruntime/imageruntime/cri.go
  pkg/daemon/util/error.go
  pkg/daemon/util/error_test.go
  test/e2e/framework/provider.go
  test/e2e/framework/test_context.go
Labels: lgtm, approved, size/M

#1505 fix: validate update AdvancedDaemonSet
  pkg/webhook/daemonset/validating/daemonset_create_update_handler.go
  pkg/webhook/daemonset/validating/daemonset_validating_handler_test.go
  pkg/webhook/daemonset/validating/daemonset_validation.go
  pkg/webhook/daemonset/validating/daemonset_validation_test.go
Labels: lgtm, approved, size/XL

#1303 Sidecar terminator ignore the exit code of the sidecar container
  pkg/controller/sidecarterminator/sidecar_terminator_controller.go
  pkg/controller/sidecarterminator/sidecar_terminator_controller_test.go
  pkg/controller/sidecarterminator/sidecar_terminator_pod_event_handler.go
  pkg/controller/sidecarterminator/sidecar_terminator_pod_event_handler_test.go
  pkg/webhook/containerrecreaterequest/mutating/crr_mutating_handler.go
  pkg/webhook/util/util.go
  test/e2e/apps/sidecarterminator.go
Labels: lgtm, approved, size/L

#1522 changelog 1.6.0
  CHANGELOG.md
Labels: lgtm, approved, size/M

#1523 fix e2e and limit workflow action permission
  .github/workflows/ci.yaml
  .github/workflows/docker-image.yaml
  .github/workflows/e2e-1.18.yaml
  .github/workflows/e2e-1.20-EphemeralJob.yaml
  .github/workflows/e2e-1.24.yaml
  .github/workflows/e2e-1.26.yaml
  .github/workflows/license.yml
  test/e2e/apps/ephemeraljob.go
  test/e2e/apps/imagelistpulljobs.go
  test/e2e/apps/statefulset.go
  test/e2e/framework/statefulset_utils.go
Labels: lgtm, approved, size/L

#1467 add_enhanced_livenessProbe_webhook
  apis/apps/v1alpha1/well_know_annotations.go
  pkg/features/kruise_features.go
  pkg/webhook/pod/mutating/enhancedlivenessprobe_handler.go
  pkg/webhook/pod/mutating/enhancedlivenessprobe_handler_test.go
  pkg/webhook/pod/mutating/pod_create_update_handler.go
  test/e2e/apps/pullimages.go
Labels: lgtm, approved, size/XL

#1526 PodWebhook=false will not disable ResourcesDeletionProtection
  CHANGELOG.md
  pkg/controller/imagepulljob/imagepulljob_controller.go
  pkg/features/kruise_features.go
Labels: lgtm, approved, size/XS

#1531 Fix when statefulset reserveOrdinals exist, scale down pvc failed
  pkg/controller/statefulset/stateful_pod_control_test.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/controller/statefulset/stateful_set_utils.go
  test/e2e/apps/statefulset.go
Labels: lgtm, approved, size/L

#1532 changelog 1.6.1 and 1.5.3
  CHANGELOG.md
Labels: lgtm, approved, size/S

#1548 fix:setup-envtest ut err, ref: https://github.com/janus-idp/operator/…
  Makefile
Labels: lgtm, approved, size/XS
