Repository openkruise/kruise, pull requests merged in 2024-04, with the labels that each got.

#1549 fix: cloneset revision update
  pkg/controller/cloneset/cloneset_status.go
Labels: lgtm, approved, size/XS

#1553 fix: workloadspread validation message
  pkg/webhook/workloadspread/validating/workloadspread_validation.go
Labels: lgtm, approved, size/XS

#1556 Fix flaky ut
  pkg/controller/uniteddeployment/revision_test.go
Labels: lgtm, approved, size/S

#1559 change log 1.6.2
  CHANGELOG.md
Labels: lgtm, approved, size/S

#1547 feature: Optimizing Pod SidecarSet webhook performance
  pkg/controller/sidecarset/sidecarset_processor.go
  pkg/util/fieldindex/register.go
  pkg/util/fieldindex/register_test.go
  pkg/webhook/pod/mutating/sidecarset.go
  pkg/webhook/pod/mutating/sidecarset_hotupgrade_test.go
  pkg/webhook/pod/mutating/sidecarset_test.go
Labels: lgtm, approved, size/L

#1565 structured logging for pkg/control
  pkg/control/pubcontrol/pub_control.go
  pkg/control/pubcontrol/pub_control_utils.go
  pkg/control/sidecarcontrol/history_control.go
  pkg/control/sidecarcontrol/sidecarset_control.go
  pkg/control/sidecarcontrol/util.go
  pkg/control/sidecarcontrol/util_hotupgrade.go
Labels: lgtm, approved, size/L

#1569 add cri version notice in v1.6.0 changelog
  CHANGELOG.md
Labels: lgtm, approved, size/XS

#1570 Add dependabot config for auto-update github-actions.
  .github/dependabot.yaml
Labels: lgtm, approved, size/S

#1580 update security policy and contacts
  README-zh_CN.md
  README.md
  SECURITY.md
  SECURITY_CONTACTS.md
  SECURITY_RESPONSE.md
  embargo-policy.md
  embargo.md
  incident-response.md
Labels: lgtm, approved, size/L

#1582 Add permission of security-events write for ghaction golangci-lint.
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/XS

#1584 fix typo and remove incident-response
  docs/proposals/20210713-sidecarsetimagepullsecrects.md
  docs/proposals/20210826-ephemeraljob.md
  incident-response.md
  pkg/controller/statefulset/stateful_pod_control_test.go
  pkg/controller/statefulset/stateful_set_utils.go
  pkg/controller/workloadspread/reschedule_test.go
  pkg/util/ownerref_test.go
  pkg/webhook/pod/mutating/container_launch_priority_initialization.go
  pkg/webhook/resourcedistribution/validating/resourcedistribution_create_update_handler.go
  typos.toml
Labels: lgtm, approved, size/L

#1586 update vuluerable package
  go.mod
  go.sum
  hack/go-get-kubernetes.sh
  pkg/daemon/criruntime/imageruntime/containerd.go
  pkg/daemon/criruntime/imageruntime/containerd_utils.go
  pkg/daemon/criruntime/imageruntime/docker.go
  pkg/daemon/criruntime/imageruntime/docker_test.go
  pkg/daemon/util/account_manager.go
  pkg/daemon/util/account_manager_test.go
Labels: lgtm, approved, size/XXL

#1579 Fixed an issue where pub webhooks unexpectedly return error when PUB is NOT FOUND
  pkg/control/pubcontrol/pub_control_utils.go
Labels: lgtm, approved, size/XS

#1566 fix: WorkloadSpread feature judgment
  pkg/controller/workloadspread/workloadspread_controller.go
  pkg/webhook/workloadspread/validating/workloadspread_create_update_handler.go
Labels: lgtm, approved, size/S

#1591 bump docker/docker,x/sys
  go.mod
  go.sum
  pkg/util/imagejob/utilfunction/imagejob_util.go
Labels: lgtm, approved, size/M

#1552 add liveness probe proposal
  docs/img/enhancedlivenessprobe_controller.png
  docs/img/enhancedlivenessprobe_node.png
  docs/img/enhancedlivenessprobe_probe_detection.png
  docs/img/global-flow-control-logic.png
  docs/img/pod_action_nodpodprobe.png
  docs/proposals/20240327-enhancedlivenessprobe.md
Labels: lgtm, approved, size/L

#1592 add 1.6.3 cve-fix changelog
  CHANGELOG.md
Labels: lgtm, approved, size/XS

#1561 [feature] When CloneSet volumeClaimTemplates changed, Pod must ReCreate update
  pkg/controller/cloneset/cloneset_controller.go
  pkg/controller/cloneset/cloneset_controller_test.go
  pkg/controller/cloneset/core/cloneset_core.go
  pkg/controller/cloneset/core/cloneset_core_test.go
  pkg/controller/cloneset/revision/cloneset_revision.go
  pkg/controller/cloneset/revision/cloneset_revision_test.go
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/features/kruise_features.go
  pkg/util/inplaceupdate/inplace_update.go
  pkg/util/inplaceupdate/inplace_update_defaults.go
  pkg/util/inplaceupdate/inplace_update_defaults_test.go
  pkg/util/volumeclaimtemplate/volume_templates_hash.go
  pkg/util/volumeclaimtemplate/volume_templates_hash_test.go
  scripts/deploy_kind.sh
  test/e2e/apps/cloneset.go
  test/e2e/framework/cloneset_util.go
Labels: lgtm, approved, size/XXL
