Repository openkruise/kruise, pull requests merged in 2024-01, with the labels that each got.

#1481 fix deleteAvailableLimit bug
  pkg/controller/cloneset/sync/cloneset_scale.go
  pkg/controller/cloneset/sync/cloneset_scale_test.go
  pkg/controller/cloneset/sync/cloneset_sync_utils.go
  pkg/controller/cloneset/sync/cloneset_sync_utils_test.go
Labels: lgtm, approved, size/L

#1482 restrict the access permissions of kruise-daemon to secrets
  Makefile
  apis/apps/defaults/v1alpha1.go
  config/daemonconfig/config/kustomization.yaml
  config/daemonconfig/config/namespace.yaml
  config/daemonconfig/config/rbac.yaml
  config/daemonconfig/kustomization.yaml
  config/default/kruise-daemon-config.yaml
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/rbac/daemon_role.yaml
  config/rbac/kustomization.yaml
  config/webhook/kustomization.yaml
  pkg/controller/imagepulljob/imagepulljob_controller.go
  pkg/controller/imagepulljob/imagepulljob_event_handler.go
  pkg/controller/imagepulljob/imagepulljob_utils.go
  pkg/util/meta.go
  pkg/util/meta_test.go
  pkg/webhook/imagepulljob/mutating/imagepulljob_create_update_handler.go
  test/e2e/apps/pullimages.go
  test/e2e/framework/imagepulljob_util.go
Labels: lgtm, approved, size/XL

#1479 sync podCondition when probe message of probeStates changed
  pkg/controller/nodepodprobe/node_pod_probe_controller.go
  pkg/util/pods.go
  pkg/util/pods_test.go
  test/e2e/apps/podprobemarker.go
  test/e2e/framework/pod_probe_marker_util.go
Labels: lgtm, approved, size/XL

#1490 Optimize container launch priority performance
  apis/apps/pub/launch_priority.go
  pkg/controller/containerlaunchpriority/container_launch_priority_controller.go
  pkg/controller/containerlaunchpriority/container_launch_priority_controller_test.go
  pkg/util/containerlaunchpriority/container_launch_priority.go
  pkg/webhook/pod/mutating/container_launch_priority_initialization.go
  pkg/webhook/pod/mutating/container_launch_priority_initialization_test.go
Labels: lgtm, approved, size/XL

#1480 fix(statefulset): fix maxUnavailable for rolling upgrades not taking …
  pkg/controller/statefulset/stateful_set_control.go
  pkg/controller/statefulset/stateful_set_control_test.go
Labels: lgtm, approved, size/L

#1487 Revert "fix deleteAvailableLimit bug (#1481)"
  pkg/controller/cloneset/sync/cloneset_scale.go
  pkg/controller/cloneset/sync/cloneset_scale_test.go
  pkg/controller/cloneset/sync/cloneset_sync_utils.go
  pkg/controller/cloneset/sync/cloneset_sync_utils_test.go
Labels: lgtm, approved, size/M

#1494 1.5.2 changelog
  CHANGELOG.md
Labels: lgtm, size/S

#1495 Changelog
  CHANGELOG.md
Labels: lgtm, size/S
