Repository openkruise/kruise, pull requests merged in 2024-08, with the labels that each got.

#1677 read certs from secrets to support external certs
  pkg/webhook/util/configuration/configuration.go
  pkg/webhook/util/controller/webhook_controller.go
  pkg/webhook/util/crd/crd.go
  pkg/webhook/util/writer/external.go
  pkg/webhook/util/writer/external_test.go
Labels: lgtm, approved, size/L

#1684 release 1.7.0 changelog
  CHANGELOG.md
  test/e2e/apps/containerrecreate.go
Labels: lgtm, approved, size/M

#1703 kruise support json log
  go.mod
  go.sum
  main.go
  pkg/webhook/pod/mutating/sidecarset.go
Labels: lgtm, approved, size/S

#1707 fix: fixed the token-permission and pinned dependencies issue
  .github/workflows/ci.yaml
  .github/workflows/codeql.yml
  .github/workflows/docker-image.yaml
  .github/workflows/e2e-1.18.yaml
  .github/workflows/e2e-1.20-EphemeralJob.yaml
  .github/workflows/e2e-1.24.yaml
  .github/workflows/e2e-1.26.yaml
  .github/workflows/e2e-1.28.yaml
  .github/workflows/license.yml
Labels: lgtm, approved, size/L

#1651 [Proposal] add proposal about resize asts pvc
  docs/img/asts-resize-pvc.png
  docs/proposals/20240626-asts-volume-resize-zh.md
  docs/proposals/20240626-asts-volume-resize.md
Labels: size/L

#1716 fix go.mod k8s.io/* from v0.30.0 to v0.28.9
  go.mod
Labels: lgtm, approved

#1696 feat: BroadcastJob Controller add disableDeepCopy options
  pkg/controller/broadcastjob/broadcastjob_controller.go
Labels: lgtm, approved, size/XS

#1717 when update cabundle reduce the invalid updated
  go.mod
  go.sum
  pkg/webhook/util/configuration/configuration.go
  pkg/webhook/util/crd/crd.go
Labels: lgtm, approved, size/S

#1719 remove normal initcontainer in sidecarset's sidecar list
  pkg/control/sidecarcontrol/util.go
  pkg/webhook/pod/mutating/sidecarset.go
Labels: lgtm, approved, size/S
