Repository openkruise/kruise, pull requests merged in 2024-06, with the labels that each got.

#1617 sidecarSet initContainer support InjectPolicy
  apis/apps/defaults/v1alpha1.go
  pkg/webhook/pod/mutating/sidecarset.go
  pkg/webhook/pod/mutating/sidecarset_test.go
  pkg/webhook/sidecarset/validating/sidecarset_create_update_handler.go
  test/e2e/apps/containerrecreate.go
  test/e2e/apps/sidecarset.go
  test/e2e/framework/containerrecreate_util.go
Labels: lgtm, approved, size/L

#1638 fix markdown linter checkout err
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/S

#1615 add ephemeraljob validating webhook
  config/webhook/manifests.yaml
  pkg/webhook/add_ephemeraljob.go
  pkg/webhook/ephemeraljob/validating/ephemeraljob_create_update_handler.go
  pkg/webhook/ephemeraljob/validating/ephemeraljob_create_update_handler_test.go
  pkg/webhook/ephemeraljob/validating/validation.go
  pkg/webhook/ephemeraljob/validating/validation_test.go
  pkg/webhook/ephemeraljob/validating/webhooks.go
  pkg/webhook/util/convertor/util.go
Labels: lgtm, approved, size/XL

#1640 fix ut error in some machines without docker auth info
  pkg/daemon/criruntime/imageruntime/helpers_test.go
Labels: lgtm, approved, size/S

#1383 Add support for credential provider plugin
  Makefile
  cmd/daemon/main.go
  pkg/daemon/criruntime/imageruntime/cri.go
  pkg/daemon/criruntime/imageruntime/docker.go
  pkg/daemon/criruntime/imageruntime/fake_plugin/main.go
  pkg/daemon/criruntime/imageruntime/fake_plugin/plugin-config.yaml
  pkg/daemon/criruntime/imageruntime/helpers_test.go
  pkg/daemon/criruntime/imageruntime/pouch.go
  pkg/util/secret/parse.go
Labels: lgtm, approved, size/L

#1641 Fix sidecarset inconsistentStatus always True bug when restart, close…
  pkg/controller/sidecarset/sidecarset_processor.go
Labels: lgtm, approved, size/XS

#1634 support `cri-dockerd.sock` for docker runtime
  pkg/daemon/criruntime/factory.go
Labels: lgtm, approved, size/S

#1643 implement StatefulSetStartOrdinal
  apis/apps/v1beta1/statefulset_types.go
  apis/apps/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_statefulsets.yaml
  config/crd/bases/apps.kruise.io_uniteddeployments.yaml
  go.mod
  pkg/controller/statefulset/stateful_pod_control.go
  pkg/controller/statefulset/stateful_pod_control_test.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/controller/statefulset/stateful_set_control_test.go
  pkg/controller/statefulset/stateful_set_utils.go
  pkg/controller/statefulset/stateful_set_utils_test.go
  pkg/features/kruise_features.go
  pkg/webhook/statefulset/validating/statefulset_validation.go
  test/e2e/apps/statefulset.go
  test/e2e/framework/ginkgowrapper.go
  test/e2e/framework/node_util.go
  test/e2e/framework/statefulset_utils.go
Labels: lgtm, approved, size/XXL

#1525 add generate helm crds scripts
  CONTRIBUTING.md
  Makefile
  scripts/generate_helm_crds.sh
Labels: lgtm, approved, size/M

#1648 opt sts updateStatefulSet
  pkg/control/sorting/pod_sorting.go
  pkg/controller/statefulset/stateful_set_control.go
  pkg/controller/statefulset/stateful_set_utils.go
Labels: lgtm, approved, size/XL
