Repository openkruise/kruise, pull requests merged in 2025-07, with the labels that each got.

#2099 Add unit tests for healthz utility
  pkg/daemon/util/healthz_test.go
Labels: lgtm, approved, size/L

#2103 Add unit tests for pkg/util/configuration
  pkg/util/configuration/configuration_test.go
Labels: lgtm, approved, size/L

#2111 Fix: non-percentage string value for maxSurge / maxUnavailable of CloneSet UpdateStrategy will be validated properly
  pkg/webhook/cloneset/validating/validation.go
  pkg/webhook/cloneset/validating/validation_test.go
Labels: lgtm, approved, size/L

#1941 Feature: Reservation Reschedule for UnitedDeployment Adaptive Strategy
  apis/apps/v1alpha1/uniteddeployment_types.go
  apis/apps/v1alpha1/well_known_labels.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_uniteddeployments.yaml
  pkg/controller/uniteddeployment/adapter/adapter.go
  pkg/controller/uniteddeployment/adapter/advanced_statefulset_adapter.go
  pkg/controller/uniteddeployment/adapter/cloneset_adapter.go
  pkg/controller/uniteddeployment/adapter/deployment_adapter.go
  pkg/controller/uniteddeployment/adapter/statefulset_adapter.go
  pkg/controller/uniteddeployment/allocator.go
  pkg/controller/uniteddeployment/allocator_test.go
  pkg/controller/uniteddeployment/revision.go
  pkg/controller/uniteddeployment/subset.go
  pkg/controller/uniteddeployment/subset_control.go
  pkg/controller/uniteddeployment/subset_control_test.go
  pkg/controller/uniteddeployment/uniteddeployment_controller.go
  pkg/controller/uniteddeployment/uniteddeployment_controller_test.go
  pkg/controller/uniteddeployment/uniteddeployment_controller_utils.go
  pkg/controller/uniteddeployment/uniteddeployment_controller_utils_test.go
  pkg/controller/uniteddeployment/uniteddeployment_update.go
  pkg/controller/util/pod_condition_utils.go
  pkg/controller/util/workload_utils.go
  pkg/controller/workloadspread/reschedule.go
  pkg/webhook/uniteddeployment/validating/uniteddeployment_validation.go
  pkg/webhook/uniteddeployment/validating/uniteddeployment_validation_test.go
  test/e2e/apps/uniteddeployment.go
  test/e2e/framework/uniteddeployment.go
Labels: lgtm, approved, size/XXL

#2118 Add unit test for `pkg/util/requeueduration/duration.go`
  pkg/util/requeueduration/duration_test.go
Labels: lgtm, approved, size/L

#2125 Fix the envtest setup to always use the latest version
  Makefile
Labels: lgtm, approved, size/XS

#2128 Add unit test for parse
  pkg/util/secret/parse_test.go
Labels: lgtm, approved, size/L
