Repository openkruise/kruise, pull requests merged in 2025-08, with the labels that each got.

#2142 add test for pkg/util/specifieddelete
  pkg/util/specifieddelete/specified_delete_test.go
Labels: lgtm, approved, size/M

#2134 fixed a typo in YYYYMMDD-template.md
  docs/proposals/YYYYMMDD-template.md
Labels: lgtm, approved, size/XS

#2156 Fix bug that caused the upgrade to block during the sidecarSet hot upgrade due to corner case.
  pkg/control/sidecarcontrol/util.go
  pkg/controller/sidecarset/sidecarset_hotupgrade.go
  pkg/controller/sidecarset/sidecarset_processor.go
Labels: lgtm, approved, size/S
