Repository openkruise/kruise, pull requests merged in 2025-04, with the labels that each got.

#1983 sort sidecarset sidecar containers
  pkg/features/kruise_features.go
  pkg/webhook/pod/mutating/sidecarset.go
  pkg/webhook/pod/mutating/sidecarset_test.go
Labels: lgtm, approved, size/M

#1990 feat: add fuzz test for workloadspread and uniteddeployment (#1713)
  .codecov.yml
  go.mod
  go.sum
  pkg/controller/uniteddeployment/fuzz_uniteddeployment_controller_test.go
  pkg/controller/workloadspread/fuzz_workloadspread_controller_test.go
  pkg/util/workloadspread/fuzz_workloadspread_utils_test.go
  pkg/webhook/uniteddeployment/validating/fuzz_uniteddeployment_validation_test.go
  pkg/webhook/workloadspread/validating/fuzz_workloadspread_validation_test.go
  test/fuzz/common.go
  test/fuzz/oss_fuzz_build.sh
  test/fuzz/uniteddeployment.go
  test/fuzz/workloadspread.go
Labels: lgtm, approved, size/XXL

#1986 fix: set the ResourceIsPod of DefaultPodValidationOptions to false
  pkg/webhook/util/pod_validation.go
  test/e2e/apps/cloneset.go
Labels: lgtm, approved, size/S

#1996 Fix: WorkloadSpread e2e tests that run in parallel frequently encounter failures.
  test/e2e/apps/workloadspread.go
  test/e2e/e2e.go
Labels: lgtm, approved, size/L

#2004 fix panic in chan pool
  pkg/daemon/imagepuller/imagepuller_worker_pool.go
Labels: lgtm, approved, size/XS

#2007 Performance optimized PodProbeMarker to reduce many invalid patch ope…
  pkg/daemon/podprobe/results_manager.go
  pkg/daemon/podprobe/results_manager_test.go
Labels: lgtm, approved, size/L

#2009 fix: NestedField function index out of range (#2008)
  pkg/util/workloadspread/utils.go
  pkg/util/workloadspread/utils_test.go
Labels: lgtm, approved, size/S

#1998 feat: add fuzz test for resourcedistribution (#1713)
  pkg/controller/resourcedistribution/fuzz_resourcedistribution_controller_test.go
  pkg/controller/uniteddeployment/fuzz_uniteddeployment_controller_test.go
  pkg/controller/workloadspread/fuzz_workloadspread_controller_test.go
  pkg/util/workloadspread/fuzz_workloadspread_utils_test.go
  pkg/webhook/resourcedistribution/validating/fuzz_resourcedistribution_validating_test.go
  pkg/webhook/uniteddeployment/validating/fuzz_uniteddeployment_validation_test.go
  pkg/webhook/workloadspread/validating/fuzz_workloadspread_validation_test.go
  test/fuzz/common.go
  test/fuzz/oss_fuzz_build.sh
  test/fuzz/resourcedistribution.go
  test/fuzz/uniteddeployment.go
  test/fuzz/workloadspread.go
Labels: lgtm, approved, size/XL
