Repository openkruise/kruise, pull requests merged in 2025-05, with the labels that each got.

#2018 v1.7.4, v1.8.1 changelog
  CHANGELOG.md
Labels: lgtm, approved, size/S

#2011 sidecarset support shareVolumeDevicePolicy
  apis/apps/v1alpha1/sidecarset_types.go
  apis/apps/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/apps.kruise.io_sidecarsets.yaml
  pkg/control/sidecarcontrol/util.go
  pkg/control/sidecarcontrol/util_test.go
  pkg/controller/sidecarset/sidecarset_processor.go
  pkg/util/pods.go
  pkg/util/pods_test.go
  pkg/webhook/pod/mutating/sidecarset.go
  pkg/webhook/pod/mutating/sidecarset_test.go
  pkg/webhook/sidecarset/validating/sidecarset_validating_test.go
Labels: lgtm, approved, size/XL

#2003 feat: podProbeMarker support http prober
  pkg/daemon/podprobe/prober.go
  pkg/daemon/podprobe/prober_test.go
  pkg/webhook/podprobemarker/validating/probe_create_update_handler.go
  pkg/webhook/podprobemarker/validating/probe_validating_test.go
  test/e2e/apps/podprobemarker.go
  test/e2e/framework/pod_probe_marker_util.go
Labels: lgtm, approved, size/XL

#2012 feat: add fuzz test ci (#1713)
  .github/workflows/ci.yaml
Labels: lgtm, approved, size/M

#2021 feat: add fuzz test doc (#1713)
  test/fuzz/README-zh_CN.md
  test/fuzz/README.md
Labels: lgtm, approved, size/L

#2022 set upstream after changing to <project> dir
  CONTRIBUTING.md
Labels: lgtm, approved, size/XS

#2020 init sclist only when enable StatefulSetAutoResizePVCGate
  pkg/controller/statefulset/statefulset_controller.go
Labels: lgtm, approved, size/XS

#2034 Documentation: Replace placeholder $LINK with actual Embargo Policy l…
  SECURITY_CONTACTS.md
Labels: lgtm, approved, size/XS

#2033 fix: Update Go Version in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: lgtm, approved, size/XS

#2010 feat: add fuzz test for sidecarset (#1713)
  pkg/control/sidecarcontrol/fuzz_util_test.go
  pkg/controller/uniteddeployment/fuzz_uniteddeployment_controller_test.go
  pkg/webhook/pod/mutating/fuzz_sidecarset_test.go
  pkg/webhook/sidecarset/validating/fuzz_sidecarset_validation_test.go
  pkg/webhook/workloadspread/validating/fuzz_workloadspread_validation_test.go
  test/fuzz/README-zh_CN.md
  test/fuzz/common.go
  test/fuzz/oss_fuzz_build.sh
  test/fuzz/sidecarset.go
  test/fuzz/uniteddeployment.go
  test/fuzz/workloadspread.go
Labels: lgtm, approved, size/XL

#2055 docs: Update embargo.md with project name and security contacts
  embargo.md
Labels: lgtm, approved, size/XS
