Repository openkruise/kruise, pull requests merged in 2025-06, with the labels that each got.

#2076 Refactor: Replace deprecated wait.PollImmediate with wait.PollUntilContextTimeout across codebase
  test/e2e/apps/daemonset.go
  test/e2e/apps/inplace_vpa.go
  test/e2e/apps/podprobemarker.go
  test/e2e/framework/broadcastjob_util.go
  test/e2e/framework/daemonset_util.go
  test/e2e/framework/ephemeraljob_utils.go
  test/e2e/framework/persistent_pod_state_util.go
  test/e2e/framework/pod_probe_marker_util.go
  test/e2e/framework/podunavailablebudget_util.go
  test/e2e/framework/resourcedistribution_utils.go
  test/e2e/framework/sidecarset_utils.go
  test/e2e/framework/statefulset_utils.go
  test/e2e/framework/util.go
Labels: lgtm, approved, size/L

#2060 fix(cloneset): process preNormal hook while enable FeatureGate CloneSetEventHandlerOptimization
  pkg/controller/cloneset/core/cloneset_core.go
  pkg/controller/cloneset/core/cloneset_core_test.go
  test/e2e/apps/cloneset.go
  test/e2e/framework/cloneset_util.go
Labels: lgtm, approved, size/L

#2079 fix: Null-dereference READ in sidecarset (#2078)
  pkg/webhook/pod/mutating/sidecarset.go
  pkg/webhook/pod/mutating/sidecarset_test.go
Labels: lgtm, approved, size/M

#2084 fix master test error
  pkg/control/pubcontrol/pub_control_utils_test.go
  pkg/controller/podunavailablebudget/pub_controller_test.go
  test/e2e/framework/persistent_pod_state_util.go
Labels: lgtm, approved, size/S

#2087 fix(cloneset): transition pod lifecycle from PreparingNormal to Normal after scheduling when PreNormal hook is not specified
  pkg/controller/cloneset/sync/cloneset_update.go
  pkg/controller/cloneset/sync/cloneset_update_test.go
  pkg/util/pods.go
  pkg/util/pods_test.go
  test/e2e/apps/cloneset.go
  test/e2e/framework/cloneset_util.go
Labels: lgtm, approved, size/L

#2061 feature: add RESIZE action for pub protection.
  apis/policy/v1alpha1/podunavailablebudget_types.go
  pkg/control/pubcontrol/api.go
  pkg/control/pubcontrol/pub_control.go
  pkg/control/pubcontrol/pub_control_test.go
  pkg/control/pubcontrol/pub_control_utils.go
  pkg/control/pubcontrol/pub_control_utils_test.go
  pkg/features/kruise_features.go
  pkg/util/inplaceupdate/inplace_update_vertical.go
  pkg/webhook/pod/validating/pod_unavailable_budget.go
  pkg/webhook/podunavailablebudget/validating/pub_create_update_handler.go
  pkg/webhook/podunavailablebudget/validating/pub_validating_test.go
Labels: lgtm, approved, size/XL, ok-to-test

#2091 upgrade k8s and go dependency to solve security alert
  go.mod
  go.sum
Labels: lgtm, approved, size/L
