Repository openkruise/kruise, pull requests merged in 2025-03, with the labels that each got.

#1975 feat: add fuzz test for workloadspread (#1713)
  go.mod
  go.sum
  pkg/controller/workloadspread/fuzz_workloadspread_controller_test.go
  pkg/util/workloadspread/fuzz_workloadspread_utils_test.go
  pkg/util/workloadspread/utils.go
  pkg/util/workloadspread/utils_test.go
  pkg/webhook/workloadspread/validating/fuzz_workloadspread_validation_test.go
Labels: size/XL

#1976 Fix: add some logs for WorkloadSpread managing existing pods
  pkg/controller/workloadspread/workloadspread_controller.go
Labels: lgtm, approved, size/S

#1965 Fix: StatefulSet get failed in validateWorkloadSpreadSpec
  pkg/webhook/workloadspread/validating/workloadspread_validation.go
Labels: lgtm, approved, size/XS
